In [2]:
import numpy as np
import pandas as pd

def print_bold(text):
    
    bold = '\033[1m'
    nbold = '\033[0m'

    print("\n" + bold + text + nbold + "\n")

<hr style="border:2px solid black"></hr>

# <center> <font color=darkgreen>DataFrame Series (Columns)</font>  </center>

<hr style="border:2px solid black"></hr>

## <font color=blue> Section 1: Simple Column Operations

<hr style="border:1px solid black"></hr>

## Creating a DataFrame from Columns

Let us start by creating a simple DataFrame with Column 'A' = [0.1, 0.2, 0.3] and Column 'B' = [10, 20, 30].

---

In [23]:
table_df = pd.DataFrame({'A':[0.1, 0.2, 0.3],'B':[10 , 20, 30]})

table_df

     A   B
0  0.1  10
1  0.2  20
2  0.3  30

---

DataFrame columns have a type called "Series".

---

In [24]:
type(table_df['A'])

pandas.core.series.Series

---

## Adding a Column to a DataFrame

We can easily add new columns to our DataFrame objects by giving them a name and some data.

---

In [26]:
# We can copy an existing column:

table_df['C'] = table_df['A']

# We can also, make one from new data:

table_df['D'] = [7.0, 8.0, 9.0]

table_df

     A   B    C    D
0  0.1  10  0.1  7.0
1  0.2  20  0.2  8.0
2  0.3  30  0.3  9.0

---

## Renaming a column in a DataFrame

We can also change the names of the columns in our DataFrame.

---

In [29]:
table_rename_df = table_df.rename(columns = {"A" : "E"})

table_rename_df

     E   B    C    D
0  0.1  10  0.1  7.0
1  0.2  20  0.2  8.0
2  0.3  30  0.3  9.0

---

### Your Turn!

Create a table, then add a new column to it.

---

---

## Series methods [sum], [multiply], [add], ...

Every column of a DataFrame is a pandas Series object, and is equipped with many useful methods that can be used to do computations.

### Example 1: Find the sum of a column:

---

In [30]:
table_df['B'].sum()

60

---

### Example 2: Add two columns:

---

In [31]:
table_df['E'] = table_df['A'].add(table_df['B'])
table_df

     A   B    C    D     E
0  0.1  10  0.1  7.0  10.1
1  0.2  20  0.2  8.0  20.2
2  0.3  30  0.3  9.0  30.3

---

### Example 3: Multiply two columns:

---

In [32]:
table_df['F'] = table_df['A'].multiply(table_df['B'])
table_df

     A   B    C    D     E    F
0  0.1  10  0.1  7.0  10.1  1.0
1  0.2  20  0.2  8.0  20.2  4.0
2  0.3  30  0.3  9.0  30.3  9.0

---

### Example 4: Get the minimum and maximum values of a column:

---

In [33]:
f_minimum = table_df['F'].min()
f_maximum = table_df['F'].max()

print("Minimum of column 'F' is: " + str(f_minimum))
print()
print("Maximum of column 'F' is: " + str(f_maximum))

Minimum of column 'F' is: 1.0

Maximum of column 'F' is: 9.0

---

### Your Turn! In the following Code Cell:
<div style="text-align: justify">
    <ul>
        <li> Create a DataFrame object with columns A: [1, 2, 3, 4], B: [5, 6, 7, 8].</li>
        <li> After creating the table, add a new column named 'C' which contains the value of column A minus the values of Column B.</li>
        <li> Print out the info, description, and head of your final DataFrame.</li>
    </ul>
</div>

---

## Checkpoint 1:

Raise your hand and ask the instructor to come and see your work before proceeding.

<div class="alert alert-block alert-info" style="text-align: justify">
<b>Warning:</b> Do not continue until you have been marked for reaching this Checkpoint! Doing so may result in a loss of points.

<hr style="border:1px solid black"></hr>

## <font color=blue> Section 2: Real World Data

<hr style="border:1px solid black"></hr>

## Create a DataFrame with Celebrity Height Data

We now create a DataFrame from data contained in the file "celebrity-heights-.csv". This file contains a list of thousands of celebrities and data on how tall they are.

---

In [3]:
url = "https://raw.githubusercontent.com/dr-bankert-augustana/PHYS_200/refs/heads/main/celebrity-heights.csv"

celebrity_height_df = pd.read_csv(url)

---

Now that we have the data in a DataFrame, let us take a look at it.

---

In [43]:
# Get the DataFrame's Basic Info:

print_bold("Celebrity Height DataFrame Info")

print(celebrity_height_df.info())

# Get a Description of the DataFrame:

print_bold("Celebrity Height DataFrame Description:")

print(celebrity_height_df.describe())

# Take a look at the first five entries in the DataFrame:

print_bold("Celebrity_Height DataFrame Head:")

print(celebrity_height_df.head())

# Take a look at the last five entries in the DataFrame:

print_bold("Celebrity Height Dataframe Tail:")

print(celebrity_height_df.tail())

Celebrity Height DataFrame Info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5502 entries, 0 to 5501
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         5502 non-null   int64
 1   firstname  5502 non-null   object
 2   midname    340 non-null    object
 3   lastname   5416 non-null   object
 4   fullname   5502 non-null   object
 5   ftin       5502 non-null   object
 6   feet       5502 non-null   int64
 7   inches     5502 non-null   float64
 8   meters     5502 non-null   float64
 9   gender     4988 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 301.0+ KB
None

Celebrity Height DataFrame Description:

                id         feet       inches       meters
count  5502.000000  5502.000000  5502.000000  5502.000000
mean   2751.500000     5.244638     5.702225     1.743402
std    1588.434922     0.462110     3.414453     0.111375
min       1.000000     2.000000     0.000000     0.812800
25%    1376.250000     5.000000     3.000000     1.663700
50%    2751.500000     5.000000     6.000000     1.739900
75%    4126.750000     5.000000     8.500000     1.822450
max    5502.000000     8.000000    11.750000     2.717800

Celebrity_Height DataFrame Head:

   id firstname midname     lastname           fullname      ftin  feet  \
0   1     Verne     NaN       Troyer       Verne Troyer   2ft 8in     2
1   8     Herve     NaN  Villechaize  Herve Villechaize  3ft 10in     3
2   9     David     NaN    Rappaport    David Rappaport  3ft 11in     3
3   2      Tony     NaN          Cox           Tony Cox   3ft 6in     3
4   3   Warwick     NaN        Davis      Warwick Davis   3ft 6in     3

   inches  meters gender
0     8.0  0.8128      M
1    10.0  1.1684      M
2    11.0  1.1938      M
3     6.0  1.0668      M
4     6.0  1.0668      M

Celebrity Height Dataframe Tail:

        id firstname midname lastname         fullname        ftin  feet  \
5497  5499   General     NaN   Height   General Height   7ft 6.5in     7
5498  5498   Matthew     NaN  McGrory  Matthew McGrory     7ft 6in     7
5499  5500     Sandy     NaN    Allen      Sandy Allen  7ft 7.25in     7
5500  5501       Sun    Ming     Ming    Sun Ming Ming  7ft 8.75in     7
5501  5502    Robert     NaN   Wadlow    Robert Wadlow    8ft 11in     8

      inches   meters gender
5497    6.50  2.29870    NaN
5498    6.00  2.28600      M
5499    7.25  2.31775      F
5500    8.75  2.35585    NaN
5501   11.00  2.71780      M

---

## Create a New Column With Total Height in Inches

Now we are going to calculate the total height of each celebrity in the DataFrame and put that information into a new column called "inches_only".

---

In [146]:
celebrity_height_df["inches_only"] = celebrity_height_df["feet"] * 12 + celebrity_height_df["inches"]

---

Lets take a look at our new DataFrame object by calling "info()", "description()", "head()", and "tail()". 

We should see that the new DataFrame contains a new column that contains each celebrity's height as measured only in inches.

---

In [46]:
print_bold("Celebrity Height DataFrame Info")
print(celebrity_height_df.info())
print_bold("Celebrity Height DataFrame Description:")
print(celebrity_height_df.describe())
print_bold("Celebrity_Height DataFrame Head:")
print(celebrity_height_df.head())
print_bold("Celebrity Height Dataframe Tail:")
print(celebrity_height_df.tail())

Celebrity Height DataFrame Info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5502 entries, 0 to 5501
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           5502 non-null   int64
 1   firstname    5502 non-null   object
 2   midname      340 non-null    object
 3   lastname     5416 non-null   object
 4   fullname     5502 non-null   object
 5   ftin         5502 non-null   object
 6   feet         5502 non-null   int64
 7   inches       5502 non-null   float64
 8   meters       5502 non-null   float64
 9   gender       4988 non-null   object
 10  inches_only  5502 non-null   float64
dtypes: float64(3), int64(2), object(6)
memory usage: 343.9+ KB
None

Celebrity Height DataFrame Description:

                id         feet       inches       meters  inches_only
count  5502.000000  5502.000000  5502.000000  5502.000000  5502.000000
mean   2751.500000     5.244638     5.702225     1.743402    68.637884
std    1588.434922     0.462110     3.414453     0.111375     4.384831
min       1.000000     2.000000     0.000000     0.812800    32.000000
25%    1376.250000     5.000000     3.000000     1.663700    65.500000
50%    2751.500000     5.000000     6.000000     1.739900    68.500000
75%    4126.750000     5.000000     8.500000     1.822450    71.750000
max    5502.000000     8.000000    11.750000     2.717800   107.000000

Celebrity_Height DataFrame Head:

   id firstname midname     lastname           fullname      ftin  feet  \
0   1     Verne     NaN       Troyer       Verne Troyer   2ft 8in     2
1   8     Herve     NaN  Villechaize  Herve Villechaize  3ft 10in     3
2   9     David     NaN    Rappaport    David Rappaport  3ft 11in     3
3   2      Tony     NaN          Cox           Tony Cox   3ft 6in     3
4   3   Warwick     NaN        Davis      Warwick Davis   3ft 6in     3

   inches  meters gender  inches_only
0     8.0  0.8128      M         32.0
1    10.0  1.1684      M         46.0
2    11.0  1.1938      M         47.0
3     6.0  1.0668      M         42.0
4     6.0  1.0668      M         42.0

Celebrity Height Dataframe Tail:

        id firstname midname lastname         fullname        ftin  feet  \
5497  5499   General     NaN   Height   General Height   7ft 6.5in     7
5498  5498   Matthew     NaN  McGrory  Matthew McGrory     7ft 6in     7
5499  5500     Sandy     NaN    Allen      Sandy Allen  7ft 7.25in     7
5500  5501       Sun    Ming     Ming    Sun Ming Ming  7ft 8.75in     7
5501  5502    Robert     NaN   Wadlow    Robert Wadlow    8ft 11in     8

      inches   meters gender  inches_only
5497    6.50  2.29870    NaN        90.50
5498    6.00  2.28600      M        90.00
5499    7.25  2.31775      F        91.25
5500    8.75  2.35585    NaN        92.75
5501   11.00  2.71780      M       107.00

---

### Your Turn! In the following Code Cell:
<div style="text-align: justify">
   Add a new column to the celebrity height dataframe that gives the height in centimeters.
</div>

---

---
## <font color=blue> Section 3: Data Queries
---

## Create a New DataFrame Based on Celebrity First Name

Next, we create a new DataFrame object that only contains celebrities whose first name is "Matthew".

In [48]:
matthew_only = celebrity_height_df[celebrity_height_df["firstname"] == "Matthew"]

matthew_only.head(10)

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
247,3697,Matthew,NaN,Rhys,Matthew Rhys,5ft 10.5in,5,10.50,1.79070,M,70.50
315,3317,Matthew,John,Armstrong,Matthew John Armstrong,5ft 10in,5,10.00,1.77800,M,70.00
525,3527,Matthew,NaN,Settle,Matthew Settle,5ft 10in,5,10.00,1.77800,M,70.00
600,3991,Matthew,NaN,Perry,Matthew Perry,5ft 11.25in,5,11.25,1.80975,M,71.25
664,4055,Matthew,NaN,Lewis,Matthew Lewis,5ft 11.5in,5,11.50,1.81610,M,71.50
872,3886,Matthew,NaN,McConaughey,Matthew McConaughey,5ft 11in,5,11.00,1.80340,M,71.00
882,3896,Matthew,NaN,Morrison,Matthew Morrison,5ft 11in,5,11.00,1.80340,M,71.00
2499,1521,Matthew,NaN,Horne,Matthew Horne,5ft 6in,5,6.00,1.67640,M,66.00
2715,2188,Matthew,NaN,Broderick,Matthew Broderick,5ft 7.5in,5,7.50,1.71450,M,67.50
2770,2243,Matthew,NaN,Lawrence,Matthew Lawrence,5ft 7.5in,5,7.50,1.71450,M,67.50

If we want to, we can restrict our DataFrame even more. Let's only grab the celebrities named "Matthew" that are at least six feet tall.

In [50]:
six_foot_matthews = celebrity_height_df[(celebrity_height_df["firstname"] == "Matthew") & (celebrity_height_df["feet"] >= 6)]

six_foot_matthews.head(10)

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
4648,4538,Matthew,NaN,Davis,Matthew Davis,6ft 1in,6,1.00,1.85420,M,73.00
4678,4568,Matthew,Gray,Gubler,Matthew Gray Gubler,6ft 1in,6,1.00,1.85420,M,73.00
4868,5064,Matthew,NaN,Marsden,Matthew Marsden,6ft 2.5in,6,2.50,1.89230,M,74.50
4967,4887,Matthew,NaN,Fox,Matthew Fox,6ft 2in,6,2.00,1.87960,M,74.00
4974,4894,Matthew,NaN,Goode,Matthew Goode,6ft 2in,6,2.00,1.87960,M,74.00
5100,5227,Matthew,NaN,Modine,Matthew Modine,6ft 3.25in,6,3.25,1.91135,M,75.25
5122,5248,Matthew,NaN,Lillard,Matthew Lillard,6ft 3.5in,6,3.50,1.91770,M,75.50
5205,5161,Matthew,NaN,MacFadyen,Matthew MacFadyen,6ft 3in,6,3.00,1.90500,M,75.00
5406,5398,Matthew,NaN,Kelly,Matthew Kelly,6ft 5in,6,5.00,1.95580,M,77.00
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M,90.00

We have seen that we can effectively carve out slices of data from our DataFrames. However, the above method both looks and feels a bit clunky.

Fortunately, there is a simpler, more natural feeling way to accomplish the same result using the <b>query()</b> function.

In [51]:
six_foot_matthews2 = celebrity_height_df.query('firstname == "Matthew" and feet >= 6')

six_foot_matthews2.head(10)

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
4648,4538,Matthew,NaN,Davis,Matthew Davis,6ft 1in,6,1.00,1.85420,M,73.00
4678,4568,Matthew,Gray,Gubler,Matthew Gray Gubler,6ft 1in,6,1.00,1.85420,M,73.00
4868,5064,Matthew,NaN,Marsden,Matthew Marsden,6ft 2.5in,6,2.50,1.89230,M,74.50
4967,4887,Matthew,NaN,Fox,Matthew Fox,6ft 2in,6,2.00,1.87960,M,74.00
4974,4894,Matthew,NaN,Goode,Matthew Goode,6ft 2in,6,2.00,1.87960,M,74.00
5100,5227,Matthew,NaN,Modine,Matthew Modine,6ft 3.25in,6,3.25,1.91135,M,75.25
5122,5248,Matthew,NaN,Lillard,Matthew Lillard,6ft 3.5in,6,3.50,1.91770,M,75.50
5205,5161,Matthew,NaN,MacFadyen,Matthew MacFadyen,6ft 3in,6,3.00,1.90500,M,75.00
5406,5398,Matthew,NaN,Kelly,Matthew Kelly,6ft 5in,6,5.00,1.95580,M,77.00
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M,90.00

Let's suppose that you aren't interested in all the celebrities named "Matthew", but are instead interested in a specific list of celebrities.

For example, lets use the cast of Star Trek: The Next Generation. We'll start by making a list of the names.

In [52]:
list_of_celebrities = ["Patrick Stewart", "Brent Spiner", "Jonathan Frakes", "Gates McFadden", "Levar Burton", "Michael Dorn", "Marina Sirtis"]

Next, we'll look at our DataFrame and pick out only celebrities whose full name is in that list using the <b>isin()</b> function.

In [53]:
star_trek_tng_cast = celebrity_height_df[celebrity_height_df["fullname"].isin(list_of_celebrities)]

star_trek_tng_cast

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
540,3542,Brent,NaN,Spiner,Brent Spiner,5ft 10in,5,10.0,1.7780,M,70.0
1467,572,Marina,NaN,Sirtis,Marina Sirtis,5ft 3in,5,3.0,1.6002,F,63.0
2778,2251,Gates,NaN,McFadden,Gates McFadden,5ft 7.5in,5,7.5,1.7145,NaN,67.5
2898,1887,Levar,NaN,Burton,Levar Burton,5ft 7in,5,7.0,1.7018,NaN,67.0
4084,3076,Patrick,NaN,Stewart,Patrick Stewart,5ft 9in,5,9.0,1.7526,M,69.0
5112,5238,Jonathan,NaN,Frakes,Jonathan Frakes,6ft 3.5in,6,3.5,1.9177,M,75.5
5167,5123,Michael,NaN,Dorn,Michael Dorn,6ft 3in,6,3.0,1.9050,M,75.0

Again, we can also accomplish this task using the <b>query()</b> function.

In [55]:
star_trek_tng_cast2 = celebrity_height_df.query("fullname in @list_of_celebrities")

star_trek_tng_cast2

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
540,3542,Brent,NaN,Spiner,Brent Spiner,5ft 10in,5,10.0,1.7780,M,70.0
1467,572,Marina,NaN,Sirtis,Marina Sirtis,5ft 3in,5,3.0,1.6002,F,63.0
2778,2251,Gates,NaN,McFadden,Gates McFadden,5ft 7.5in,5,7.5,1.7145,NaN,67.5
2898,1887,Levar,NaN,Burton,Levar Burton,5ft 7in,5,7.0,1.7018,NaN,67.0
4084,3076,Patrick,NaN,Stewart,Patrick Stewart,5ft 9in,5,9.0,1.7526,M,69.0
5112,5238,Jonathan,NaN,Frakes,Jonathan Frakes,6ft 3.5in,6,3.5,1.9177,M,75.5
5167,5123,Michael,NaN,Dorn,Michael Dorn,6ft 3in,6,3.0,1.9050,M,75.0

---
As before, the <b>query()</b> makes it easy and natural to ask multiple questions of the data at once.

Let's get only those celebrities on our list that are over six feet tall.

---

In [56]:
six_foot_star_trek_tng_cast = celebrity_height_df.query("fullname in @list_of_celebrities and feet >= 6")

six_foot_star_trek_tng_cast

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
5112,5238,Jonathan,NaN,Frakes,Jonathan Frakes,6ft 3.5in,6,3.5,1.9177,M,75.5
5167,5123,Michael,NaN,Dorn,Michael Dorn,6ft 3in,6,3.0,1.9050,M,75.0

---

### Your Turn! In the following Code Cell:
<div style="text-align: justify">
    Use the query function to try and find your favorite celebrity.
</div>

---

---
## <font color=blue> Section 3: Groupby Operations
---

## Group Celebrities Based on First Name

Lets say that we want to find out information about a specific subset within our DataFrame. We can do so by grouping our entries based on some criteria.

For example, lets group all the celebrities in our DataFrame based on their first names. The result is a <b>DataFrameGroupBy</b> object.

To narrow our focus, we are only going to keep the fullname, gender, and inches_only columns

In [73]:
grouped_by_first_name = celebrity_height_df.groupby("firstname")[["firstname", "fullname", "gender", "inches_only"]]

Let's now examine our new grouping.

In [74]:
print_bold("Grouped By First Name DataFrame Head:")
print(grouped_by_first_name.head())
print_bold("Grouped By First Name Dataframe Tail:")
print(grouped_by_first_name.tail())

Grouped By First Name DataFrame Head:

     firstname           fullname gender  inches_only
0        Verne       Verne Troyer      M        32.00
1        Herve  Herve Villechaize      M        46.00
2        David    David Rappaport      M        47.00
3         Tony           Tony Cox      M        42.00
4      Warwick      Warwick Davis      M        42.00
...        ...                ...    ...          ...
5493  Football    Football Soccer    NaN        85.00
5496      Ming           Ming Yao      F        89.00
5497   General     General Height    NaN        90.50
5499     Sandy        Sandy Allen      F        91.25
5500       Sun      Sun Ming Ming    NaN        92.75

[3782 rows x 4 columns]

Grouped By First Name Dataframe Tail:

     firstname           fullname gender  inches_only
0        Verne       Verne Troyer      M        32.00
1        Herve  Herve Villechaize      M        46.00
4      Warwick      Warwick Davis      M        42.00
5         Phil     Phil Fondacaro      M        42.00
7        Kenny        Kenny Baker      M        44.00
...        ...                ...    ...          ...
5497   General     General Height    NaN        90.50
5498   Matthew    Matthew McGrory      M        90.00
5499     Sandy        Sandy Allen      F        91.25
5500       Sun      Sun Ming Ming    NaN        92.75
5501    Robert      Robert Wadlow      M       107.00

[3782 rows x 4 columns]

It's hard to tell what's going on just from the above. Python has created a group for each unique 'firstname' entry and assigned each row to its appropriate group.

We can, however, perform operations on the groupings. For example, we can find the average height of each celebrity of a given first name using the <b>mean()</b> function.

Note that we use the flag: <b>numeric_only = True</b>. This tells Python, that we only want to average values that are numbers.

If we try to average values that are not numbers, we get nonsense values.

In [82]:
average_height_by_name = celebrity_height_df.groupby("firstname").mean(numeric_only = True)

average_height_by_name

               id  feet     inches    meters  inches_only
firstname
A          1818.5   5.0   5.625000  1.666875    65.625000
A. J.      2053.5   5.0   7.250000  1.708150    67.250000
ANT        1412.0   5.0   6.000000  1.676400    66.000000
Aaliyah    1005.0   5.0   5.000000  1.651000    65.000000
Aaron      3428.5   5.0  10.041667  1.779058    70.041667
...           ...   ...        ...       ...          ...
Zoe        1735.4   5.0   6.100000  1.678940    66.100000
Zoie       1600.0   5.0   6.000000  1.676400    66.000000
Zooey      1072.0   5.0   5.000000  1.651000    65.000000
Zsa         726.0   5.0   4.000000  1.625600    64.000000
Zuleikha   1805.0   5.0   6.500000  1.689100    66.500000

[2032 rows x 5 columns]

We can instead find the shortest celebrity with each name by using the <b>min()</b> function

In [83]:
shortest_by_name = celebrity_height_df.groupby("firstname").mean(numeric_only = True)

shortest_by_name

               id  feet     inches    meters  inches_only
firstname
A          1818.5   5.0   5.625000  1.666875    65.625000
A. J.      2053.5   5.0   7.250000  1.708150    67.250000
ANT        1412.0   5.0   6.000000  1.676400    66.000000
Aaliyah    1005.0   5.0   5.000000  1.651000    65.000000
Aaron      3428.5   5.0  10.041667  1.779058    70.041667
...           ...   ...        ...       ...          ...
Zoe        1735.4   5.0   6.100000  1.678940    66.100000
Zoie       1600.0   5.0   6.000000  1.676400    66.000000
Zooey      1072.0   5.0   5.000000  1.651000    65.000000
Zsa         726.0   5.0   4.000000  1.625600    64.000000
Zuleikha   1805.0   5.0   6.500000  1.689100    66.500000

[2032 rows x 5 columns]

Or, we can find the tallest celebrity with each name by using the <b>max()</b> function.

In [84]:
tallest_by_name = celebrity_height_df.groupby("firstname").mean(numeric_only = True)

tallest_by_name

               id  feet     inches    meters  inches_only
firstname
A          1818.5   5.0   5.625000  1.666875    65.625000
A. J.      2053.5   5.0   7.250000  1.708150    67.250000
ANT        1412.0   5.0   6.000000  1.676400    66.000000
Aaliyah    1005.0   5.0   5.000000  1.651000    65.000000
Aaron      3428.5   5.0  10.041667  1.779058    70.041667
...           ...   ...        ...       ...          ...
Zoe        1735.4   5.0   6.100000  1.678940    66.100000
Zoie       1600.0   5.0   6.000000  1.676400    66.000000
Zooey      1072.0   5.0   5.000000  1.651000    65.000000
Zsa         726.0   5.0   4.000000  1.625600    64.000000
Zuleikha   1805.0   5.0   6.500000  1.689100    66.500000

[2032 rows x 5 columns]

We can even make up our own functions to parse the data by using the <b>agg()</b> function which stands for "aggregate".

For example, lets create a function that gives us the ratio of tallest to shortest celebrity for each first name.

In [106]:
def ratio_of_tallest_to_shortest(height_list):
    tallest = max(height_list)
    shortest = min(height_list)
    return tallest / shortest

height_ratio_by_name = celebrity_height_df.groupby("firstname")[["inches_only"]].agg(ratio_of_tallest_to_shortest)

height_ratio_by_name = height_ratio_by_name.rename(columns = {"inches_only" : "height_ratio"})

height_ratio_by_name

           height_ratio
firstname
A              1.142857
A. J.          1.022556
ANT            1.000000
Aaliyah        1.000000
Aaron          1.055147
...                 ...
Zoe            1.129032
Zoie           1.000000
Zooey          1.000000
Zsa            1.000000
Zuleikha       1.000000

[2032 rows x 1 columns]

Now that we have this new information, we can ask other questions, such as: "What is the biggest ratio for any name?" and "Which name has the biggest ratio?"

In [107]:
# What is the biggest ratio?

max_ratio = height_ratio_by_name.max()[0]

print("Max Ratio is: " + str(max_ratio))
print()

# What name has this ratio?

height_ratio_by_name.query("height_ratio == @max_ratio")

Max Ratio is: 1.8953488372093024

           height_ratio
firstname
Michael        1.895349

Another thing that we can do is rearrange the information in our DataFrame based on a condition that we set using the <b>sort_values()</b> function.

To show this, lets sort our celebrities by their height as listed in the "inches_only" column.

In [108]:
celebrity_height_df.sort_values("inches_only")

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.00,0.81280,M,32.00
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.00,1.06680,M,42.00
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.00,1.06680,M,42.00
5,4,Phil,NaN,Fondacaro,Phil Fondacaro,3ft 6in,3,6.00,1.06680,M,42.00
6,5,Michael,J,Anderson,Michael J Anderson,3ft 7in,3,7.00,1.09220,M,43.00
...,...,...,...,...,...,...,...,...,...,...,...
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M,90.00
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN,90.50
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F,91.25
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN,92.75
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M,107.00

In the above example, we sorted the values from least to greatest, we can do the opposite by setting the flag: <b>ascending = False</b>.

In [109]:
celebrity_height_df.sort_values("inches_only", ascending = False)

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M,107.00
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN,92.75
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F,91.25
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN,90.50
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M,90.00
...,...,...,...,...,...,...,...,...,...,...,...
6,5,Michael,J,Anderson,Michael J Anderson,3ft 7in,3,7.00,1.09220,M,43.00
5,4,Phil,NaN,Fondacaro,Phil Fondacaro,3ft 6in,3,6.00,1.06680,M,42.00
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.00,1.06680,M,42.00
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.00,1.06680,M,42.00
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.00,0.81280,M,32.00

Now, we have a new way of finding the shortest or tallest celebrity with a given name by sorting the DataFrame and finding the first time a particular name appears.

For example, lets find the shortest celebrity with each name by using <b>agg()</b> to find the first time a name appears in a list sorted from shortest to tallest.

In [112]:
def get_first_item(list_of_names):
    return list_of_names.iloc[0]

celebrity_height_df.sort_values("inches_only").groupby("firstname").agg(get_first_item)

,id,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
firstname,,,,,,,,,,
A,168,J,Langer,A J Langer,5ft 1.25in,5,1.25,1.55575,NaN,61.25
A. J.,1737,NaN,Cook,A. J. Cook,5ft 6.5in,5,6.50,1.68910,NaN,66.50
ANT,1412,NaN,NaN,ANT,5ft 6in,5,6.00,1.67640,NaN,66.00
Aaliyah,1005,NaN,NaN,Aaliyah,5ft 5in,5,5.00,1.65100,F,65.00
Aaron,2598,NaN,Stanford,Aaron Stanford,5ft 8in,5,8.00,1.72720,M,68.00
...,...,...,...,...,...,...,...,...,...,...
Zoe,350,NaN,Tapper,Zoe Tapper,5ft 2in,5,2.00,1.57480,F,62.00
Zoie,1600,NaN,Palmer,Zoie Palmer,5ft 6in,5,6.00,1.67640,F,66.00
Zooey,1072,NaN,Deschanel,Zooey Deschanel,5ft 5in,5,5.00,1.65100,NaN,65.00
Zsa,726,Zsa,Gabor,Zsa Zsa Gabor,5ft 4in,5,4.00,1.62560,NaN,64.00
Zuleikha,1805,NaN,Robinson,Zuleikha Robinson,5ft 6.5in,5,6.50,1.68910,NaN,66.50

As with anything in programming, there is more than one way to do a task.

Let us repeat the above using the <b>groupby()</b> and <b>first()</b> functions.

In [115]:
celebrity_height_df.sort_values("inches_only").groupby("firstname").first()

,id,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
firstname,,,,,,,,,,
A,168,J,Langer,A J Langer,5ft 1.25in,5,1.25,1.55575,None,61.25
A. J.,1737,None,Cook,A. J. Cook,5ft 6.5in,5,6.50,1.68910,None,66.50
ANT,1412,None,None,ANT,5ft 6in,5,6.00,1.67640,None,66.00
Aaliyah,1005,None,None,Aaliyah,5ft 5in,5,5.00,1.65100,F,65.00
Aaron,2598,None,Stanford,Aaron Stanford,5ft 8in,5,8.00,1.72720,M,68.00
...,...,...,...,...,...,...,...,...,...,...
Zoe,350,None,Tapper,Zoe Tapper,5ft 2in,5,2.00,1.57480,F,62.00
Zoie,1600,None,Palmer,Zoie Palmer,5ft 6in,5,6.00,1.67640,F,66.00
Zooey,1072,None,Deschanel,Zooey Deschanel,5ft 5in,5,5.00,1.65100,None,65.00
Zsa,726,Zsa,Gabor,Zsa Zsa Gabor,5ft 4in,5,4.00,1.62560,None,64.00
Zuleikha,1805,None,Robinson,Zuleikha Robinson,5ft 6.5in,5,6.50,1.68910,None,66.50

We can even do some silly things like add up all the heights of each celebrity for a given first name using <b>sum()</b>.

In [116]:
# What is the total height of each celebrity name?

total_height = celebrity_height_df.groupby("firstname").sum(numeric_only = True)

total_height

              id  feet  inches    meters  inches_only
firstname
A           3637    10   11.25   3.33375       131.25
A. J.       4107    10   14.50   3.41630       134.50
ANT         1412     5    6.00   1.67640        66.00
Aaliyah     1005     5    5.00   1.65100        65.00
Aaron      20571    30   60.25  10.67435       420.25
...          ...   ...     ...       ...          ...
Zoe         8677    25   30.50   8.39470       330.50
Zoie        1600     5    6.00   1.67640        66.00
Zooey       1072     5    5.00   1.65100        65.00
Zsa          726     5    4.00   1.62560        64.00
Zuleikha    1805     5    6.50   1.68910        66.50

[2032 rows x 5 columns]

We can also do something more sensible, like ask how many celebrities are there in our data of a given name using <b>value_counts()</b>.

In [123]:
name_count = celebrity_height_df["firstname"].value_counts()

name_count

Michael    84
John       76
James      64
David      59
Robert     50
           ..
Burgess     1
Cherie      1
Tinsel      1
Lainie      1
Sun         1
Name: firstname, Length: 2032, dtype: int64

Now, let's suppose that we want to do something more complicated. 

Say that we want to compute the ratio of each celebrity's height to the average height of other celebrities with their same first name.

In [124]:
average_height = celebrity_height_df.groupby("firstname").mean(numeric_only = True)

celebrities_indexed_by_name = celebrity_height_df.set_index("firstname")

fraction_height_df = celebrities_indexed_by_name / average_height

fraction_height_df

,feet,ftin,fullname,gender,id,inches,inches_only,lastname,meters,midname
firstname,,,,,,,,,,
A,1.0,NaN,NaN,NaN,0.092384,0.222222,0.933333,NaN,0.933333,NaN
A,1.0,NaN,NaN,NaN,1.907616,1.777778,1.066667,NaN,1.066667,NaN
A. J.,1.0,NaN,NaN,NaN,0.845873,0.896552,0.988848,NaN,0.988848,NaN
A. J.,1.0,NaN,NaN,NaN,1.154127,1.103448,1.011152,NaN,1.011152,NaN
ANT,1.0,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,NaN
...,...,...,...,...,...,...,...,...,...,...
Zoe,1.0,NaN,NaN,NaN,1.172064,1.147541,1.013616,NaN,1.013616,NaN
Zoie,1.0,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,NaN
Zooey,1.0,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,NaN
Zsa,1.0,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,NaN
Zuleikha,1.0,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,NaN

---

In the above example, we divided all the values in "celebrities_indexed_by_name" with all the values in "average_height".

Whenever there was a numeric value, the result was straight forward. However, non-numeric values can't be divided and thus gave us "NaN" or "Not a Number".

Let's redo that, but instead of dividing all of the values, lets just divide the "inches_only" columns and create a new column with the ratio.

To accomplish this, we are first going to use <b>reindex()</b> to organize the DataFrame based on firstname and fullname.

---

In [128]:
df_indexed_by_firstname_and_fullname = celebrity_height_df.set_index(["firstname", "fullname"]) 
df_indexed_by_firstname_and_fullname

,,id,midname,lastname,ftin,feet,inches,meters,gender,inches_only
firstname,fullname,,,,,,,,,
Verne,Verne Troyer,1,NaN,Troyer,2ft 8in,2,8.00,0.81280,M,32.00
Herve,Herve Villechaize,8,NaN,Villechaize,3ft 10in,3,10.00,1.16840,M,46.00
David,David Rappaport,9,NaN,Rappaport,3ft 11in,3,11.00,1.19380,M,47.00
Tony,Tony Cox,2,NaN,Cox,3ft 6in,3,6.00,1.06680,M,42.00
Warwick,Warwick Davis,3,NaN,Davis,3ft 6in,3,6.00,1.06680,M,42.00
...,...,...,...,...,...,...,...,...,...,...
General,General Height,5499,NaN,Height,7ft 6.5in,7,6.50,2.29870,NaN,90.50
Matthew,Matthew McGrory,5498,NaN,McGrory,7ft 6in,7,6.00,2.28600,M,90.00
Sandy,Sandy Allen,5500,NaN,Allen,7ft 7.25in,7,7.25,2.31775,F,91.25
Sun,Sun Ming Ming,5501,Ming,Ming,7ft 8.75in,7,8.75,2.35585,NaN,92.75
Robert,Robert Wadlow,5502,NaN,Wadlow,8ft 11in,8,11.00,2.71780,M,107.00

---

### Example Operation

We are going to compute the ratio of the height of each celebrity to the average height for their first name.

<b> STEP 1:</b> We start by finding the average height in inches for each first name.

---

In [150]:
average_height = celebrity_height_df.groupby("firstname").mean(numeric_only = True)

average_height = average_height.rename(columns = {"inches_only" : "average_height_in_inches"})

average_height

               id  feet     inches    meters  average_height_in_inches
firstname
A          1818.5   5.0   5.625000  1.666875                 65.625000
A. J.      2053.5   5.0   7.250000  1.708150                 67.250000
ANT        1412.0   5.0   6.000000  1.676400                 66.000000
Aaliyah    1005.0   5.0   5.000000  1.651000                 65.000000
Aaron      3428.5   5.0  10.041667  1.779058                 70.041667
...           ...   ...        ...       ...                       ...
Zoe        1735.4   5.0   6.100000  1.678940                 66.100000
Zoie       1600.0   5.0   6.000000  1.676400                 66.000000
Zooey      1072.0   5.0   5.000000  1.651000                 65.000000
Zsa         726.0   5.0   4.000000  1.625600                 64.000000
Zuleikha   1805.0   5.0   6.500000  1.689100                 66.500000

[2032 rows x 5 columns]

---

<b> STEP 2:</b> We divide the height of each celebrity in "inches_only" with the average height in inches for their first name.

---

In [187]:
ratio = (df_indexed_by_firstname_and_fullname["inches_only"] / average_height["average_height_in_inches"])

ratio

firstname  fullname
Verne      Verne Troyer         1.000000
Herve      Herve Villechaize    1.000000
David      David Rappaport      0.663080
Tony       Tony Cox             0.603974
Warwick    Warwick Davis        1.000000
                                  ...
General    General Height       1.000000
Matthew    Matthew McGrory      1.239751
Sandy      Sandy Allen          1.000000
Sun        Sun Ming Ming        1.000000
Robert     Robert Wadlow        1.505558
Length: 5502, dtype: float64

---

<b> STEP 3:</b> We reset the index to look like the original DataFrame format and name our new column.

---

In [188]:
ratio_reindexed = ratio.reset_index()

ratio_reindexed = ratio_reindexed.rename(columns={0:'height_ratio_by_firstname'})

ratio_reindexed

     firstname           fullname  height_ratio_by_firstname
0        Verne       Verne Troyer                   1.000000
1        Herve  Herve Villechaize                   1.000000
2        David    David Rappaport                   0.663080
3         Tony           Tony Cox                   0.603974
4      Warwick      Warwick Davis                   1.000000
...        ...                ...                        ...
5497   General     General Height                   1.000000
5498   Matthew    Matthew McGrory                   1.239751
5499     Sandy        Sandy Allen                   1.000000
5500       Sun      Sun Ming Ming                   1.000000
5501    Robert      Robert Wadlow                   1.505558

[5502 rows x 3 columns]

---

<b> STEP 4:</b> Finally, we add our new column of data to the original DataFrame.

---

In [191]:
height_ratio_df = celebrity_height_df

height_ratio_df["height_ratio_by_firstname"] = ratio_reindexed["height_ratio_by_firstname"]

print_bold("Height Ratio DataFrame Info")
print(height_ratio_df.info())
print_bold("Height Ratio DataFrame Description:")
print(height_ratio_df.describe())
print_bold("Height Ratio DataFrame Head:")
print(height_ratio_df.head())
print_bold("Height Ratio Dataframe Tail:")
print(height_ratio_df.tail())

Height Ratio DataFrame Info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5502 entries, 0 to 5501
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         5502 non-null   int64
 1   firstname                  5502 non-null   object
 2   midname                    340 non-null    object
 3   lastname                   5416 non-null   object
 4   fullname                   5502 non-null   object
 5   ftin                       5502 non-null   object
 6   feet                       5502 non-null   int64
 7   inches                     5502 non-null   float64
 8   meters                     5502 non-null   float64
 9   gender                     4988 non-null   object
 10  inches_only                5502 non-null   float64
 11  height_ratio_by_firstname  5502 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 386.9+ KB
None

Height Ratio DataFrame Description:

                id         feet       inches       meters  inches_only  \
count  5502.000000  5502.000000  5502.000000  5502.000000  5502.000000
mean   2751.500000     5.244638     5.702225     1.743402    68.637884
std    1588.434922     0.462110     3.414453     0.111375     4.384831
min       1.000000     2.000000     0.000000     0.812800    32.000000
25%    1376.250000     5.000000     3.000000     1.663700    65.500000
50%    2751.500000     5.000000     6.000000     1.739900    68.500000
75%    4126.750000     5.000000     8.500000     1.822450    71.750000
max    5502.000000     8.000000    11.750000     2.717800   107.000000

       height_ratio_by_firstname
count                5502.000000
mean                    1.000000
std                     0.039787
min                     0.603974
25%                     0.981078
50%                     1.000000
75%                     1.019456
max                     1.505558

Height Ratio DataFrame Head:

   id firstname midname     lastname           fullname      ftin  feet  \
0   1     Verne     NaN       Troyer       Verne Troyer   2ft 8in     2
1   8     Herve     NaN  Villechaize  Herve Villechaize  3ft 10in     3
2   9     David     NaN    Rappaport    David Rappaport  3ft 11in     3
3   2      Tony     NaN          Cox           Tony Cox   3ft 6in     3
4   3   Warwick     NaN        Davis      Warwick Davis   3ft 6in     3

   inches  meters gender  inches_only  height_ratio_by_firstname
0     8.0  0.8128      M         32.0                   1.000000
1    10.0  1.1684      M         46.0                   1.000000
2    11.0  1.1938      M         47.0                   0.663080
3     6.0  1.0668      M         42.0                   0.603974
4     6.0  1.0668      M         42.0                   1.000000

Height Ratio Dataframe Tail:

        id firstname midname lastname         fullname        ftin  feet  \
5497  5499   General     NaN   Height   General Height   7ft 6.5in     7
5498  5498   Matthew     NaN  McGrory  Matthew McGrory     7ft 6in     7
5499  5500     Sandy     NaN    Allen      Sandy Allen  7ft 7.25in     7
5500  5501       Sun    Ming     Ming    Sun Ming Ming  7ft 8.75in     7
5501  5502    Robert     NaN   Wadlow    Robert Wadlow    8ft 11in     8

      inches   meters gender  inches_only  height_ratio_by_firstname
5497    6.50  2.29870    NaN        90.50                   1.000000
5498    6.00  2.28600      M        90.00                   1.239751
5499    7.25  2.31775      F        91.25                   1.000000
5500    8.75  2.35585    NaN        92.75                   1.000000
5501   11.00  2.71780      M       107.00                   1.505558

---

We can now explore this new DataFrame object. Lets start by looking back at the Star Trek cast.

---

In [195]:
tng_ratio = height_ratio_df[ratio_reindexed["fullname"].isin(list_of_celebrities)]

tng_ratio

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only,height_ratio_by_firstname
540,3542,Brent,NaN,Spiner,Brent Spiner,5ft 10in,5,10.0,1.7780,M,70.0,1.000000
1467,572,Marina,NaN,Sirtis,Marina Sirtis,5ft 3in,5,3.0,1.6002,F,63.0,1.000000
2778,2251,Gates,NaN,McFadden,Gates McFadden,5ft 7.5in,5,7.5,1.7145,NaN,67.5,1.000000
2898,1887,Levar,NaN,Burton,Levar Burton,5ft 7in,5,7.0,1.7018,NaN,67.0,1.000000
4084,3076,Patrick,NaN,Stewart,Patrick Stewart,5ft 9in,5,9.0,1.7526,M,69.0,0.964403
5112,5238,Jonathan,NaN,Frakes,Jonathan Frakes,6ft 3.5in,6,3.5,1.9177,M,75.5,1.064317
5167,5123,Michael,NaN,Dorn,Michael Dorn,6ft 3in,6,3.0,1.9050,M,75.0,1.059491

---

We can query our DataFrame to find only those celebrities who are taller than average for their name.

---

In [196]:
taller_than_average = celebrity_height_df.query("height_ratio_by_firstname > 1")

taller_than_average

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only,height_ratio_by_firstname
53,88,Mae,NaN,Whitman,Mae Whitman,5ft 0.5in,5,0.50,1.53670,F,60.50,1.004149
92,169,Lady,NaN,Sovereign,Lady Sovereign,5ft 1.25in,5,1.25,1.55575,NaN,61.25,1.002045
139,3589,Andy,NaN,Dick,Andy Dick,5ft 10.25in,5,10.25,1.78435,F,70.25,1.014964
140,3590,Alex,NaN,Dimitriades,Alex Dimitriades,5ft 10.25in,5,10.25,1.78435,F,70.25,1.019347
142,3592,Karen,NaN,Gillan,Karen Gillan,5ft 10.25in,5,10.25,1.78435,F,70.25,1.075941
...,...,...,...,...,...,...,...,...,...,...,...,...
5494,5492,Ian,NaN,Whyte,Ian Whyte,7ft 1in,7,1.00,2.15900,M,85.00,1.225716
5495,5496,Kevin,Peter,Hall,Kevin Peter Hall,7ft 2in,7,2.00,2.18440,M,86.00,1.203232
5496,5497,Ming,NaN,Yao,Ming Yao,7ft 5in,7,5.00,2.26060,F,89.00,1.171053
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M,90.00,1.239751
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M,107.00,1.505558

---

We can also get more specific and find only those celebrities named "Mary" who are shorter than average for their name.

---

In [199]:
short_mary = celebrity_height_df.query("firstname == 'Mary' and height_ratio_by_firstname < 1")

short_mary

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only,height_ratio_by_firstname
28,29,Mary,Kate,Olsen,Mary Kate Olsen,4ft 11in,4,11.0,1.4986,F,59.0,0.906199
1012,143,Mary,Kay,Place,Mary Kay Place,5ft 1in,5,1.0,1.5494,F,61.0,0.936917
1329,434,Mary,Kay,Bergman,Mary Kay Bergman,5ft 3in,5,3.0,1.6002,F,63.0,0.967636
1500,899,Mary,J.,Blige,Mary J. Blige,5ft 4.5in,5,4.5,1.6383,F,64.5,0.990675
1569,968,Mary,NaN,Tamm,Mary Tamm,5ft 4.5in,5,4.5,1.6383,F,64.5,0.990675
1736,792,Mary,Stuart,Masterson,Mary Stuart Masterson,5ft 4in,5,4.0,1.6256,F,64.0,0.982995
2123,1174,Mary,Elizabeth,Mastrantonio,Mary Elizabeth Mastrantonio,5ft 5in,5,5.0,1.6510,F,65.0,0.998354

---

You might notice that there are a lot of "NaN" entries in our DataFrame. (Apparently there isn't midname data for a lot of the celebrities.)                                              

If we wanted to only focus on entries that had a complete set of data, we can do so by using the <b>dropna()</b> function.

---

In [197]:
celebrity_height_df_no_gaps = celebrity_height_df.dropna()

celebrity_height_df_no_gaps

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only,height_ratio_by_firstname
6,5,Michael,J,Anderson,Michael J Anderson,3ft 7in,3,7.000,1.092200,M,43.000,0.607442
18,36,Jada,Pinkett,Smith,Jada Pinkett Smith,4ft 11.5in,4,11.500,1.511300,F,59.500,1.000000
19,37,Marissa,Jaret,Winokur,Marissa Jaret Winokur,4ft 11.5in,4,11.500,1.511300,F,59.500,1.000000
21,22,Tammy,Faye,Bakker,Tammy Faye Bakker,4ft 11in,4,11.000,1.498600,F,59.000,0.941489
28,29,Mary,Kate,Olsen,Mary Kate Olsen,4ft 11in,4,11.000,1.498600,F,59.000,0.906199
...,...,...,...,...,...,...,...,...,...,...,...,...
5447,5438,Omar,Benson,Miller,Omar Benson Miller,6ft 6in,6,6.000,1.981200,M,78.000,1.072165
5457,5448,Ryan,Lee,Stiles,Ryan Lee Stiles,6ft 6in,6,6.000,1.981200,M,78.000,1.091545
5483,5484,Andre,The,Giant,Andre The Giant,7ft 0in,7,0.000,2.133600,M,84.000,1.154639
5490,5495,Kareem,Abdul,Jabbar,Kareem Abdul Jabbar,7ft 1.625in,7,1.625,2.174875,M,85.625,1.000000
5495,5496,Kevin,Peter,Hall,Kevin Peter Hall,7ft 2in,7,2.000,2.184400,M,86.000,1.203232

---

We can, if we want, only drop the entries with missing midname values, but keep entries that might be missing other data.

---

In [198]:
celebrity_height_df_with_midname = celebrity_height_df.dropna(subset = "midname")

celebrity_height_df_with_midname

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only,height_ratio_by_firstname
6,5,Michael,J,Anderson,Michael J Anderson,3ft 7in,3,7.000,1.092200,M,43.000,0.607442
18,36,Jada,Pinkett,Smith,Jada Pinkett Smith,4ft 11.5in,4,11.500,1.511300,F,59.500,1.000000
19,37,Marissa,Jaret,Winokur,Marissa Jaret Winokur,4ft 11.5in,4,11.500,1.511300,F,59.500,1.000000
21,22,Tammy,Faye,Bakker,Tammy Faye Bakker,4ft 11in,4,11.000,1.498600,F,59.000,0.941489
28,29,Mary,Kate,Olsen,Mary Kate Olsen,4ft 11in,4,11.000,1.498600,F,59.000,0.906199
...,...,...,...,...,...,...,...,...,...,...,...,...
5457,5448,Ryan,Lee,Stiles,Ryan Lee Stiles,6ft 6in,6,6.000,1.981200,M,78.000,1.091545
5483,5484,Andre,The,Giant,Andre The Giant,7ft 0in,7,0.000,2.133600,M,84.000,1.154639
5490,5495,Kareem,Abdul,Jabbar,Kareem Abdul Jabbar,7ft 1.625in,7,1.625,2.174875,M,85.625,1.000000
5495,5496,Kevin,Peter,Hall,Kevin Peter Hall,7ft 2in,7,2.000,2.184400,M,86.000,1.203232
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.750,2.355850,NaN,92.750,1.000000