<a href="https://colab.research.google.com/github/dr-bankert-augustana/PHYS_200/blob/main/Lessons/Module_1/PHYS_200_Lesson_1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a name="Notebook-Start"></a>

---

<font size = 7> <b> Lesson 1.4 (Pandas and DataFrames) </b> </font>

---

<font size = 5> <b> Notebook Index </b> </font>

1.  [Learning Outcomes](#Learning-Outcomes)

2.  [Introduction](#Introduction)

7.  [Appendix A: New Term Definitions](#Appendix-Definitions)
$
\newcommand{\lsum}{\displaystyle \sum\limits_{i=1}^{N}}
\newcommand{\parens}[1]{\left(#1\right)}
\newcommand{\dsfrac}[2]{\displaystyle\frac{#1}{#2}}
\newcommand{\dpfrac}[2]{\displaystyle\parens{\frac{#1}{#2}}}
\newcommand{\parderiv}[2]{\dsfrac{\partial #1}{\partial #2}}
\newcommand{\spc}{\hspace{0.1 pc}}
\newcommand{\ra}{\Rightarrow}
\newcommand{\of}[1]{{\scriptsize (#1)}}
\newcommand{\rule}{\Huge \hspace{-0.2 pc} \displaystyle\frac{\hspace{20 pc}}{\hspace{20 pc}}}
\newcommand{\mps}{\spc \frac{\textrm{m}}{\textrm{s}}}
\newcommand{\mpss}{\spc \frac{\textrm{m}}{\textrm{s}^2}}
$

<a name="Learning-Outcomes"></a>

---

<font size = 6> <b> 1. Learning Outcomes </b> </font>

---

By the end of this lesson, students will:

[Return to Top](#Notebook-Start)

<a name="Introduction"></a>

---

<font size = 6> <b> 2. Introduction </b> </font>

---

<font size = 5> <b> 2.1 What is Pandas? </b> </font>

<p align="justify">
In computational physics (and any kind of scientific computing) managing, analyzing, and visualizing data efficiently is essential. The Pandas library in Python is a powerful and flexible tool designed specifically for data manipulation and analysis. At its core, Pandas introduces two primary data structures.
</p>

  * The <a href = #Definition-Series></b>Series</b></a> (a one-dimensional array)
  
  * The <a href = #Definition-Series></b>DataFrame</b></a> (a two-dimensional table similar to an Excel spreadsheet).
  
<br>

<p align="justify">
These new data structures allow us to label our data, perform complex operations with simple syntax, and handle missing values or mixed data types gracefully.
</p>

[Return to Top](#Notebook-Start)

<a name="Creating-DF"></a>

---

<font size = 6> <b> 3. Creating DataFrames </b> </font>

---

<font size=5><b>3.1 Creating DataFrames From Dictionaries</b></font>

<p align="justify">
One of the most straightforward ways to create a DataFrame in Pandas is by using a Python dictionary. In this approach, each key in the dictionary represents a column name, and the corresponding value is a list (or array) containing the data for that column. Pandas automatically aligns these values by row, as long as the lists are of equal length.
</p>

<br>

<p align="justify">
This method is especially useful when you already have structured data in Python (for example, experimental measurements or simulation results stored in variables) and you want to organize them into a tabular format for further analysis.
</p>

<br>

<b>Code Example:</b>

In the following code cell, we create a simple DataFrame from some synthetic experimental data.

In [2]:
# Import the Pandas Library:

import pandas as pd

# Create a dictionary of data:

data = {
    "Time (s)": [0, 1, 2, 3, 4],
    "Position (m)": [0, 2.5, 10, 22.5, 40],
    "Velocity (m/s)": [0, 5, 10, 15, 20]
}

# Convert the dictionary into a DataFrame:

df = pd.DataFrame(data)

# Display the DataFrame:

display(df)

   Time (s)  Position (m)  Velocity (m/s)
0         0           0.0               0
1         1           2.5               5
2         2          10.0              10
3         3          22.5              15
4         4          40.0              20

<b>Understanding the Output</b>

<p align="justify">
This printed table looks very similar to what you'd see in a spreadsheet like Excel or Google Sheets:
</p>

  * <b>Columns:</b> Each column corresponds to one of the keys from the dictionary. In this case, we have three columns: <code>Time (s)</code>, <code>Position (m)</code>, and <code>Velocity (m/s)</code>. These serve the same purpose as column headers in a spreadsheet, labeling the type of data in each column.

  * <b>Rows:</b> Each row contains a single set of related data points; one time value, one position, and one velocity. These rows represent observations or measurements taken at different points in time.

  * <b>Index column (on the far left):</b> By default, Pandas automatically adds an index column starting from 0. This index uniquely identifies each row, similar to row numbers in a spreadsheet. While it doesn't carry physical meaning in this example, it becomes very useful when accessing or referencing specific rows programmatically.

<br>

<p align="justify">
So, in essence, the Pandas DataFrame behaves much like a digital spreadsheet, but with the added power of Python. As we see in this lesson, you can apply mathematical operations, filter rows, compute statistics, and generate plots all from this structured format, making it a key tool in your computational physics toolkit.
</p>

<center>$\rule$</center>
<font size=5><b>3.2 Creating a DataFrame from a CSV File</b></font>

<p align="justify">
In real-world physics work, it's common to store data in external files; especially CSV (Comma-Separated Values) files. These are simple text files where each line represents a row of data, and values are separated by commas. Think of it as a stripped-down spreadsheet that can be easily shared and read by many programs. In fact, you can export a spreadsheet from any common program (such as Excel, Google Sheets, etc) as a CSV file.
</p>

<br>

<p align="justify">
Pandas makes it incredibly easy to read data from a CSV file and convert it into a DataFrame using the <code>read_csv()</code> function.
</p>

<br>

<b>Code Example:</b>

In the following code cell, we read in the data from a CSV file into a Pandas DataFrame.

In [5]:
# Set the location of the CSV file (can be local or a website):

url = "https://raw.githubusercontent.com/dr-bankert-augustana/PHYS_200/refs/heads/main/Data/Module_1/celebrity-heights.csv"

# Turn the CSV data into a Pandas DataFrame:

celebrity_height_df = pd.read_csv(url)

# Display the DataFrame:

display(celebrity_height_df)

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.00,0.81280,M
1,8,Herve,NaN,Villechaize,Herve Villechaize,3ft 10in,3,10.00,1.16840,M
2,9,David,NaN,Rappaport,David Rappaport,3ft 11in,3,11.00,1.19380,M
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.00,1.06680,M
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.00,1.06680,M
...,...,...,...,...,...,...,...,...,...,...
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M

<center>$\rule$</center>
<font size=5><b>3.3 Creating a DataFrame from Columns</b></font>

Let us start by creating a simple DataFrame with Column 'A' = [0.1, 0.2, 0.3] and Column 'B' = [10, 20, 30].

<b>Code Example</b>

In [24]:
table_df = pd.DataFrame({'A':[0.1, 0.2, 0.3],'B':[10 , 20, 30]})

display(table_df)

     A   B
0  0.1  10
1  0.2  20
2  0.3  30

<center>$\rule$</center>
<font size=5><b>3.4 Adding a Column to a DataFrame</b></font>

We can easily add new columns to our DataFrame objects by giving them a name and some data.

<br>

<b>Code Example</b>

In [25]:
# We can copy an existing column:

table_df['C'] = table_df['A']

# We can also, make one from new data:

table_df['D'] = [7.0, 8.0, 9.0]

table_df

     A   B    C    D
0  0.1  10  0.1  7.0
1  0.2  20  0.2  8.0
2  0.3  30  0.3  9.0

<center>$\rule$</center>
<font size=5><b>3.5 Renaming a column in a DataFrame</b></font>

We can also change the names of the columns in our DataFrame.

<br>

<b>Code Example</b>

In [29]:
table_rename_df = table_df.rename(columns = {"A" : "E"})

table_rename_df

     E   B    C    D
0  0.1  10  0.1  7.0
1  0.2  20  0.2  8.0
2  0.3  30  0.3  9.0

---

## Series methods [sum], [multiply], [add], ...

Every column of a DataFrame is a pandas Series object, and is equipped with many useful methods that can be used to do computations.

### Example 1: Find the sum of a column:

---

In [30]:
print(table_df['B'].sum())

60

---

### Example 2: Add two columns:

---

In [31]:
table_df['E'] = table_df['A'].add(table_df['B'])
table_df

     A   B    C    D     E
0  0.1  10  0.1  7.0  10.1
1  0.2  20  0.2  8.0  20.2
2  0.3  30  0.3  9.0  30.3

---

### Example 3: Multiply two columns:

---

In [32]:
table_df['F'] = table_df['A'].multiply(table_df['B'])
table_df

     A   B    C    D     E    F
0  0.1  10  0.1  7.0  10.1  1.0
1  0.2  20  0.2  8.0  20.2  4.0
2  0.3  30  0.3  9.0  30.3  9.0

---

### Example 4: Get the minimum and maximum values of a column:

---

In [33]:
f_minimum = table_df['F'].min()
f_maximum = table_df['F'].max()

print("Minimum of column 'F' is: " + str(f_minimum))
print()
print("Maximum of column 'F' is: " + str(f_maximum))

Minimum of column 'F' is: 1.0

Maximum of column 'F' is: 9.0

[Return to Top](#Notebook-Start)

<a name="Explore-DF"></a>

---

<font size = 6> <b> 4. Exploring a DataFrame </b> </font>

---

<font size=5><b>4.1 Methods for Exploring the DataFrame</b></font>

<p align="justify">
Once you've loaded data into a Pandas DataFrame (whether from a dictionary, CSV file, or another source) it's important to understand what's in it and whether it looks right before jumping into analysis. Pandas provides several built-in methods to help us quickly explore the dataset.
</p>

<center>$\rule$</center>
<font size=5><b>4.2 <code>info()</code>: Structure and Metadata</b></font>

This method gives you a concise summary of the DataFrame’s structure, including:

  * The number of rows and columns

  * Column names and data types (int64, float64, object, etc.)

  * Number of non-null (i.e. non-missing) values in each column

  * Memory usage

<br>

<p align="justify">
<b>Why it's useful:</b> Helps you quickly check for missing data and see if the data types are appropriate (e.g. no text where numbers should be).
</p>

<br>

<b>Code Example:</b>

In the following code cell, we use <code>info()</code> to look at our celebrity heights DataFrame.

In [7]:
# Display the Output of info():

display(celebrity_height_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5502 entries, 0 to 5501
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         5502 non-null   int64
 1   firstname  5502 non-null   object
 2   midname    340 non-null    object
 3   lastname   5416 non-null   object
 4   fullname   5502 non-null   object
 5   ftin       5502 non-null   object
 6   feet       5502 non-null   int64
 7   inches     5502 non-null   float64
 8   meters     5502 non-null   float64
 9   gender     4988 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 430.0+ KB

None

<center>$\rule$</center>
<font size=5><b>4.3 <code>df.describe()</code>: Summary Statistics</b></font>

This method computes common statistical summaries for each numeric column, such as:

* Count

* Mean

* Standard deviation

* Min and max

* 25th, 50th (median), and 75th percentiles

<br>

<b>Why it's useful</b>: Provides a quick overview of the data's distribution and helps spot unusual values (e.g., extreme outliers or zero variance).

<br>

<b>Code Example:</b>

In the following code cell, we use <code>describe()</code> to look at our celebrity heights DataFrame.

<center>$\rule$</center>
<font size=5><b>4.4 <code>head(n)</code>: Display First n Rows (Default: 5)</b></font>

Displays the first few rows of the DataFrame. This is often your first stop after loading data to verify that everything looks as expected (column names, data format, etc.).

<br>

<b>Code Example:</b>

In the following code cell, we use <code>head(n)</code> to look at our celebrity heights DataFrame.

In [10]:
# Display the first 5 rows of the celebrity heights DataFrame:

print("First 5 rows:")

display(celebrity_height_df.head())

print()

# Display the first 10 rows of the celebrity heights DataFrame:

print("First 10 rows:")

display(celebrity_height_df.head(10))

First 5 rows:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.0,0.8128,M
1,8,Herve,NaN,Villechaize,Herve Villechaize,3ft 10in,3,10.0,1.1684,M
2,9,David,NaN,Rappaport,David Rappaport,3ft 11in,3,11.0,1.1938,M
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.0,1.0668,M
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.0,1.0668,M

First 10 rows:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.0,0.81280,M
1,8,Herve,NaN,Villechaize,Herve Villechaize,3ft 10in,3,10.0,1.16840,M
2,9,David,NaN,Rappaport,David Rappaport,3ft 11in,3,11.0,1.19380,M
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.0,1.06680,M
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.0,1.06680,M
5,4,Phil,NaN,Fondacaro,Phil Fondacaro,3ft 6in,3,6.0,1.06680,M
6,5,Michael,J,Anderson,Michael J Anderson,3ft 7in,3,7.0,1.09220,M
7,6,Kenny,NaN,Baker,Kenny Baker,3ft 8in,3,8.0,1.11760,M
8,7,Billy,NaN,Barty,Billy Barty,3ft 9in,3,9.0,1.14300,M
9,10,Kiran,NaN,Shah,Kiran Shah,4ft 1.7in,4,1.7,1.26238,F

<center>$\rule$</center>
<font size=5><b>4.5 <code>tail(n)</code>: Display Last n Rows (Default: 5)</b></font>

Displays the last few rows of the DataFrame. This is useful to:

  * See the end of a time series

  * Verify that data loaded completely

  * Check for anomalies or formatting issues at the bottom of the file

<br>

<b>Code Example:</b>

In the following code cell, we use <code>tail(n)</code> to look at our celebrity heights DataFrame.

In [11]:
# Display the last 5 rows of the celebrity heights DataFrame:

print("Last 5 rows:")

display(celebrity_height_df.tail())

print()

# Display the last 10 rows of the celebrity heights DataFrame:

print("Last 10 rows:")

display(celebrity_height_df.tail(10))

Last 5 rows:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M

Last 10 rows:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
5492,5490,Dalip,NaN,Singh,Dalip Singh,7ft 1in,7,1.00,2.15900,NaN
5493,5491,Football,NaN,Soccer,Football Soccer,7ft 1in,7,1.00,2.15900,NaN
5494,5492,Ian,NaN,Whyte,Ian Whyte,7ft 1in,7,1.00,2.15900,M
5495,5496,Kevin,Peter,Hall,Kevin Peter Hall,7ft 2in,7,2.00,2.18440,M
5496,5497,Ming,NaN,Yao,Ming Yao,7ft 5in,7,5.00,2.26060,F
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M

<center>$\rule$</center>
<font size=5><b>4.6 Other Useful Commands For Investigating DataFrames</b></font>

  * <b>df.columns</b>:
  
    * Returns a list-like object containing the column labels.

    * Useful for checking column names or looping through columns.

  * <b>df.index</b>:

    * Returns the row index of the DataFrame (default is a RangeIndex).

    * Important if you're dealing with custom indices like timestamps or labels.

  * <b>df.shape</b>:

    * Returns a tuple representing the dimensions of the DataFrame: (rows, columns).

  * <b>df.dtypes</b>:

    * Shows the data type of each column (e.g., float64, int64, object).

    * Helpful when debugging unexpected behavior in calculations.

  * <b>df.nunique()</b>:

    * Returns the number of unique values in each column.

    * Good for identifying categorical vs. continuous data, or detecting duplicates.

  * <b>df.isnull().sum()</b>:

    * Identifies missing values by column.

    * Essential for cleaning data before analysis or plotting.

  * <b>df.sample(n)</b>:

    * Returns a random sample of n rows from the DataFrame.

    * Great for large datasets when you just want to inspect a few random entries.

  * <b>df["column_name"].value_counts()</b>:

    * For a single column, shows how often each unique value appears (useful for categorical or discrete data).

[Return to Top](#Notebook-Start)

<a name="Select-DF"></a>

---

<font size = 6> <b> 5. Selecting Data in a DataFrame </b> </font>

---

<font size=5><b>5.1 Bracket Notation []</b></font>

<p align="justify">
Once we have loaded and explored our DataFrame, the next step is accessing specific columns or subsets of data. One of the most common and flexible ways to do this is using bracket selection, which looks like: <code>DataFrame[selector]</code>
</p>

<br>

<p align="justify">
Depending on what we put inside the brackets, we can select a column, multiple columns, or filter rows using logical conditions.
</p>

<center>$\rule$</center>
<font size=5><b>5.2 Selecting a Single Column</b></font>

<p align="justify">
If we pass a string (column name) inside the brackets, Pandas returns a Series (a one-dimensional view of that column). This works like selecting a column in a spreadsheet by its header. The result behaves like a list but with labels (index) attached.
</p>

<br>

><b>Note:</b><p align="justify">
We can also call up a column by using: <code>DF_Name.Column_Name</code>
</p>

<br>

<b>Code Example:</b>

In [14]:
# Select the 'firstname' column of the celebrity heights data:

first_names = celebrity_height_df['firstname']

# Display the firstnames data:

display(first_names)

# Select the 'lastname' column of the celebrity heights data:

last_names = celebrity_height_df.lastname

# Display the lastnames data:

display(last_names)

0         Verne
1         Herve
2         David
3          Tony
4       Warwick
         ...
5497    General
5498    Matthew
5499      Sandy
5500        Sun
5501     Robert
Name: firstname, Length: 5502, dtype: object

0            Troyer
1       Villechaize
2         Rappaport
3               Cox
4             Davis
           ...
5497         Height
5498        McGrory
5499          Allen
5500           Ming
5501         Wadlow
Name: lastname, Length: 5502, dtype: object

<center>$\rule$</center>
<font size=5><b>5.3 Selecting a Multiple Columns</b></font>

<p align="justify">
To select more than one column, pass in a list of column names inside the brackets: <code>subset_df = df[[column_1, column_2]]</code>. Now you get a new DataFrame with just those columns. Similar to hiding other columns in a spreadsheet.
</p>

<br>

<b>Code Example:</b>

In [15]:
# Select the 'firstname' and 'lastname' columns of the celebrity heights data:

names = celebrity_height_df[['firstname', 'lastname']]

# Display the subset data:

display(names)

     firstname     lastname
0        Verne       Troyer
1        Herve  Villechaize
2        David    Rappaport
3         Tony          Cox
4      Warwick        Davis
...        ...          ...
5497   General       Height
5498   Matthew      McGrory
5499     Sandy        Allen
5500       Sun         Ming
5501    Robert       Wadlow

[5502 rows x 2 columns]

<center>$\rule$</center>
<font size=5><b>5.4 Selecting Rows with Logical Conditions</b></font>

<p align="justify">
You can also use bracket selection with boolean expressions to filter rows. This is incredibly powerful for working with physical measurements or simulation outputs. This is called using a <b>Boolean Mask</b>. Example: <code>subset = df[boolean_mask]</code>. This filters the DataFrame and only returns rows that meet the condition, just like using filters in Excel or Google Sheets.
</p>

><b>Note:</b><p align="justify">
You can build more complex filters by combining multiple conditions.
</p>

<br>

<b>Code Example:</b>

In [22]:
# Create a subset of people who are over 2.2 meters tall:

tall_people = celebrity_height_df[celebrity_height_df['meters'] > 2.2]

# Display the subset data:

print("Tall People:")
display(tall_people)
print()

# Create a subset of people who are between 1.6 and 1.7 meters tall:

medium_tall_people = celebrity_height_df[(celebrity_height_df['meters'] > 1.6) & (celebrity_height_df['meters'] < 1.7)]

# Display the subset data:

print("Medium Tall People:")
display(medium_tall_people)
print()

# Create a subset of people who are shorter than 1.1 meters and taller than 2.2  meters tall:

short_and_tall_people = celebrity_height_df[(celebrity_height_df['meters'] < 1.1) | (celebrity_height_df['meters'] > 2.2)]

# Display the subset data:

print("Short and Tall People:")
display(short_and_tall_people)

Tall People:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
5496,5497,Ming,NaN,Yao,Ming Yao,7ft 5in,7,5.00,2.26060,F
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M

Medium Tall People:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
1252,591,Jillian,NaN,Barberie,Jillian Barberie,5ft 3.25in,5,3.25,1.60655,F
1253,592,Vanessa,NaN,Paradis,Vanessa Paradis,5ft 3.25in,5,3.25,1.60655,F
1254,593,Annabella,NaN,Sciorra,Annabella Sciorra,5ft 3.25in,5,3.25,1.60655,F
1255,594,Amy,NaN,Adams,Amy Adams,5ft 3.5in,5,3.50,1.61290,F
1256,595,Samaire,NaN,Armstrong,Samaire Armstrong,5ft 3.5in,5,3.50,1.61290,NaN
...,...,...,...,...,...,...,...,...,...,...
2672,1694,Henry,NaN,Winkler,Henry Winkler,5ft 6in,5,6.00,1.67640,M
2673,1695,Kate,NaN,Winslet,Kate Winslet,5ft 6in,5,6.00,1.67640,F
2674,1696,Evan,Rachel,Wood,Evan Rachel Wood,5ft 6in,5,6.00,1.67640,M
2675,1697,Bill,NaN,Wyman,Bill Wyman,5ft 6in,5,6.00,1.67640,M
2676,1698,Loretta,NaN,Young,Loretta Young,5ft 6in,5,6.00,1.67640,F

Short and Tall People:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.00,0.81280,M
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.00,1.06680,M
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.00,1.06680,M
5,4,Phil,NaN,Fondacaro,Phil Fondacaro,3ft 6in,3,6.00,1.06680,M
6,5,Michael,J,Anderson,Michael J Anderson,3ft 7in,3,7.00,1.09220,M
5496,5497,Ming,NaN,Yao,Ming Yao,7ft 5in,7,5.00,2.26060,F
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M

<center>$\rule$</center>
<font size=5><b>5.5 <code>.loc()</code> and <code>.iloc()</code></b></font>

<p align="justify">
Pandas provides two powerful accessors:
</p>

  * .loc[]: selects by label

  * .iloc[]: selects by integer position

<br>

<p align="justify">
These are much more versatile than [] alone, especially when selecting specific rows and columns at the same time or when doing row slicing.
</p>

  * .loc[]: Selection by Label

    * Syntax: <code>df.loc[row_selector, column_selector]</code>

  * Selecting Rows by Index Label

    * Syntax: <code>df.loc[0]  # Selects the row with index label 0</code>

  * Row Slicing by Label

    * Syntax: <code>df.loc[0:2]</code>

    ><b>Note:</b> <code>.loc[]</code> slicing includes the stop value (unlike standard Python slicing).

  * Selecting Specific Rows and Columns by Label

    * Syntax: <code>df.loc[0:2, ["Time (s)", "Velocity (m/s)"]]</code>

    * This returns rows 0 through 2, and only the "Time" and "Velocity" columns.

  * .iloc[]: Selection by Integer Position

    * Syntax: df.iloc[row_index, column_index]

    * Use .iloc[] when you want to slice or select based on numerical index positions, just like Python lists.

  * Selecting a Row by Integer Index

    * df.iloc[0]  # First row

  * Row Slicing by Position

    * df.iloc[0:3]  # Rows 0 through 2 (excludes stop index, like Python slicing)

  * Selecting Specific Rows and Columns by Position

    * df.iloc[0:3, 0:2]  # First 3 rows, first 2 columns

[Return to Top](#Notebook-Start)

<a name="Select-DF"></a>

---

<font size = 6> <b> 6. Groupby Operations </b> </font>

---

## Group Celebrities Based on First Name

Lets say that we want to find out information about a specific subset within our DataFrame. We can do so by grouping our entries based on some criteria.

For example, lets group all the celebrities in our DataFrame based on their first names. The result is a <b>DataFrameGroupBy</b> object.

To narrow our focus, we are only going to keep the fullname, gender, and inches_only columns

In [35]:
celebrity_height_df["inches_only"] = celebrity_height_df["feet"] * 12 + celebrity_height_df["inches"]

grouped_by_first_name = celebrity_height_df.groupby("firstname")[["firstname", "fullname", "gender", "inches_only"]]

Let's now examine our new grouping.

In [38]:
print("Grouped By First Name DataFrame Head:")
print()
print(grouped_by_first_name.head())
print()
print()
print("Grouped By First Name Dataframe Tail:")
print()
print(grouped_by_first_name.tail())

Grouped By First Name DataFrame Head:

     firstname           fullname gender  inches_only
0        Verne       Verne Troyer      M        32.00
1        Herve  Herve Villechaize      M        46.00
2        David    David Rappaport      M        47.00
3         Tony           Tony Cox      M        42.00
4      Warwick      Warwick Davis      M        42.00
...        ...                ...    ...          ...
5493  Football    Football Soccer    NaN        85.00
5496      Ming           Ming Yao      F        89.00
5497   General     General Height    NaN        90.50
5499     Sandy        Sandy Allen      F        91.25
5500       Sun      Sun Ming Ming    NaN        92.75

[3782 rows x 4 columns]


Grouped By First Name Dataframe Tail:

     firstname           fullname gender  inches_only
0        Verne       Verne Troyer      M        32.00
1        Herve  Herve Villechaize      M        46.00
4      Warwick      Warwick Davis      M        42.00
5         Phil     Phil Fondacaro      M        42.00
7        Kenny        Kenny Baker      M        44.00
...        ...                ...    ...          ...
5497   General     General Height    NaN        90.50
5498   Matthew    Matthew McGrory      M        90.00
5499     Sandy        Sandy Allen      F        91.25
5500       Sun      Sun Ming Ming    NaN        92.75
5501    Robert      Robert Wadlow      M       107.00

[3782 rows x 4 columns]

It's hard to tell what's going on just from the above. Python has created a group for each unique 'firstname' entry and assigned each row to its appropriate group.

We can, however, perform operations on the groupings. For example, we can find the average height of each celebrity of a given first name using the <b>mean()</b> function.

Note that we use the flag: <b>numeric_only = True</b>. This tells Python, that we only want to average values that are numbers.

If we try to average values that are not numbers, we get nonsense values.

In [39]:
average_height_by_name = celebrity_height_df.groupby("firstname").mean(numeric_only = True)

average_height_by_name

               id  feet     inches    meters  inches_only
firstname
A          1818.5   5.0   5.625000  1.666875    65.625000
A. J.      2053.5   5.0   7.250000  1.708150    67.250000
ANT        1412.0   5.0   6.000000  1.676400    66.000000
Aaliyah    1005.0   5.0   5.000000  1.651000    65.000000
Aaron      3428.5   5.0  10.041667  1.779058    70.041667
...           ...   ...        ...       ...          ...
Zoe        1735.4   5.0   6.100000  1.678940    66.100000
Zoie       1600.0   5.0   6.000000  1.676400    66.000000
Zooey      1072.0   5.0   5.000000  1.651000    65.000000
Zsa         726.0   5.0   4.000000  1.625600    64.000000
Zuleikha   1805.0   5.0   6.500000  1.689100    66.500000

[2032 rows x 5 columns]

We can instead find the shortest celebrity with each name by using the <b>min()</b> function

In [40]:
shortest_by_name = celebrity_height_df.groupby("firstname").mean(numeric_only = True)

shortest_by_name

               id  feet     inches    meters  inches_only
firstname
A          1818.5   5.0   5.625000  1.666875    65.625000
A. J.      2053.5   5.0   7.250000  1.708150    67.250000
ANT        1412.0   5.0   6.000000  1.676400    66.000000
Aaliyah    1005.0   5.0   5.000000  1.651000    65.000000
Aaron      3428.5   5.0  10.041667  1.779058    70.041667
...           ...   ...        ...       ...          ...
Zoe        1735.4   5.0   6.100000  1.678940    66.100000
Zoie       1600.0   5.0   6.000000  1.676400    66.000000
Zooey      1072.0   5.0   5.000000  1.651000    65.000000
Zsa         726.0   5.0   4.000000  1.625600    64.000000
Zuleikha   1805.0   5.0   6.500000  1.689100    66.500000

[2032 rows x 5 columns]

Or, we can find the tallest celebrity with each name by using the <b>max()</b> function.

In [41]:
tallest_by_name = celebrity_height_df.groupby("firstname").mean(numeric_only = True)

tallest_by_name

               id  feet     inches    meters  inches_only
firstname
A          1818.5   5.0   5.625000  1.666875    65.625000
A. J.      2053.5   5.0   7.250000  1.708150    67.250000
ANT        1412.0   5.0   6.000000  1.676400    66.000000
Aaliyah    1005.0   5.0   5.000000  1.651000    65.000000
Aaron      3428.5   5.0  10.041667  1.779058    70.041667
...           ...   ...        ...       ...          ...
Zoe        1735.4   5.0   6.100000  1.678940    66.100000
Zoie       1600.0   5.0   6.000000  1.676400    66.000000
Zooey      1072.0   5.0   5.000000  1.651000    65.000000
Zsa         726.0   5.0   4.000000  1.625600    64.000000
Zuleikha   1805.0   5.0   6.500000  1.689100    66.500000

[2032 rows x 5 columns]

We can even make up our own functions to parse the data by using the <b>agg()</b> function which stands for "aggregate".

For example, lets create a function that gives us the ratio of tallest to shortest celebrity for each first name.

In [42]:
def ratio_of_tallest_to_shortest(height_list):
    tallest = max(height_list)
    shortest = min(height_list)
    return tallest / shortest

height_ratio_by_name = celebrity_height_df.groupby("firstname")[["inches_only"]].agg(ratio_of_tallest_to_shortest)

height_ratio_by_name = height_ratio_by_name.rename(columns = {"inches_only" : "height_ratio"})

height_ratio_by_name

           height_ratio
firstname
A              1.142857
A. J.          1.022556
ANT            1.000000
Aaliyah        1.000000
Aaron          1.055147
...                 ...
Zoe            1.129032
Zoie           1.000000
Zooey          1.000000
Zsa            1.000000
Zuleikha       1.000000

[2032 rows x 1 columns]

Now that we have this new information, we can ask other questions, such as: "What is the biggest ratio for any name?" and "Which name has the biggest ratio?"

In [43]:
# What is the biggest ratio?

max_ratio = height_ratio_by_name.max()[0]

print("Max Ratio is: " + str(max_ratio))
print()

# What name has this ratio?

height_ratio_by_name.query("height_ratio == @max_ratio")

Max Ratio is: 1.8953488372093024

/tmp/ipython-input-3765096514.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  max_ratio = height_ratio_by_name.max()[0]

           height_ratio
firstname
Michael        1.895349

Another thing that we can do is rearrange the information in our DataFrame based on a condition that we set using the <b>sort_values()</b> function.

To show this, lets sort our celebrities by their height as listed in the "inches_only" column.

In [44]:
celebrity_height_df.sort_values("inches_only")

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.00,0.81280,M,32.00
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.00,1.06680,M,42.00
5,4,Phil,NaN,Fondacaro,Phil Fondacaro,3ft 6in,3,6.00,1.06680,M,42.00
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.00,1.06680,M,42.00
6,5,Michael,J,Anderson,Michael J Anderson,3ft 7in,3,7.00,1.09220,M,43.00
...,...,...,...,...,...,...,...,...,...,...,...
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M,90.00
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN,90.50
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F,91.25
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN,92.75
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M,107.00

In the above example, we sorted the values from least to greatest, we can do the opposite by setting the flag: <b>ascending = False</b>.

In [45]:
celebrity_height_df.sort_values("inches_only", ascending = False)

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M,107.00
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN,92.75
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F,91.25
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN,90.50
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M,90.00
...,...,...,...,...,...,...,...,...,...,...,...
6,5,Michael,J,Anderson,Michael J Anderson,3ft 7in,3,7.00,1.09220,M,43.00
5,4,Phil,NaN,Fondacaro,Phil Fondacaro,3ft 6in,3,6.00,1.06680,M,42.00
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.00,1.06680,M,42.00
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.00,1.06680,M,42.00
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.00,0.81280,M,32.00

Now, we have a new way of finding the shortest or tallest celebrity with a given name by sorting the DataFrame and finding the first time a particular name appears.

For example, lets find the shortest celebrity with each name by using <b>agg()</b> to find the first time a name appears in a list sorted from shortest to tallest.

In [46]:
def get_first_item(list_of_names):
    return list_of_names.iloc[0]

celebrity_height_df.sort_values("inches_only").groupby("firstname").agg(get_first_item)

,id,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
firstname,,,,,,,,,,
A,168,J,Langer,A J Langer,5ft 1.25in,5,1.25,1.55575,NaN,61.25
A. J.,1737,NaN,Cook,A. J. Cook,5ft 6.5in,5,6.50,1.68910,NaN,66.50
ANT,1412,NaN,NaN,ANT,5ft 6in,5,6.00,1.67640,NaN,66.00
Aaliyah,1005,NaN,NaN,Aaliyah,5ft 5in,5,5.00,1.65100,F,65.00
Aaron,2598,NaN,Stanford,Aaron Stanford,5ft 8in,5,8.00,1.72720,M,68.00
...,...,...,...,...,...,...,...,...,...,...
Zoe,350,NaN,Tapper,Zoe Tapper,5ft 2in,5,2.00,1.57480,F,62.00
Zoie,1600,NaN,Palmer,Zoie Palmer,5ft 6in,5,6.00,1.67640,F,66.00
Zooey,1072,NaN,Deschanel,Zooey Deschanel,5ft 5in,5,5.00,1.65100,NaN,65.00
Zsa,726,Zsa,Gabor,Zsa Zsa Gabor,5ft 4in,5,4.00,1.62560,NaN,64.00
Zuleikha,1805,NaN,Robinson,Zuleikha Robinson,5ft 6.5in,5,6.50,1.68910,NaN,66.50

As with anything in programming, there is more than one way to do a task.

Let us repeat the above using the <b>groupby()</b> and <b>first()</b> functions.

In [47]:
celebrity_height_df.sort_values("inches_only").groupby("firstname").first()

,id,midname,lastname,fullname,ftin,feet,inches,meters,gender,inches_only
firstname,,,,,,,,,,
A,168,J,Langer,A J Langer,5ft 1.25in,5,1.25,1.55575,None,61.25
A. J.,1737,None,Cook,A. J. Cook,5ft 6.5in,5,6.50,1.68910,None,66.50
ANT,1412,None,None,ANT,5ft 6in,5,6.00,1.67640,None,66.00
Aaliyah,1005,None,None,Aaliyah,5ft 5in,5,5.00,1.65100,F,65.00
Aaron,2598,None,Stanford,Aaron Stanford,5ft 8in,5,8.00,1.72720,M,68.00
...,...,...,...,...,...,...,...,...,...,...
Zoe,350,None,Tapper,Zoe Tapper,5ft 2in,5,2.00,1.57480,F,62.00
Zoie,1600,None,Palmer,Zoie Palmer,5ft 6in,5,6.00,1.67640,F,66.00
Zooey,1072,None,Deschanel,Zooey Deschanel,5ft 5in,5,5.00,1.65100,None,65.00
Zsa,726,Zsa,Gabor,Zsa Zsa Gabor,5ft 4in,5,4.00,1.62560,None,64.00
Zuleikha,1805,None,Robinson,Zuleikha Robinson,5ft 6.5in,5,6.50,1.68910,None,66.50

We can even do some silly things like add up all the heights of each celebrity for a given first name using <b>sum()</b>.

In [48]:
# What is the total height of each celebrity name?

total_height = celebrity_height_df.groupby("firstname").sum(numeric_only = True)

total_height

              id  feet  inches    meters  inches_only
firstname
A           3637    10   11.25   3.33375       131.25
A. J.       4107    10   14.50   3.41630       134.50
ANT         1412     5    6.00   1.67640        66.00
Aaliyah     1005     5    5.00   1.65100        65.00
Aaron      20571    30   60.25  10.67435       420.25
...          ...   ...     ...       ...          ...
Zoe         8677    25   30.50   8.39470       330.50
Zoie        1600     5    6.00   1.67640        66.00
Zooey       1072     5    5.00   1.65100        65.00
Zsa          726     5    4.00   1.62560        64.00
Zuleikha    1805     5    6.50   1.68910        66.50

[2032 rows x 5 columns]

We can also do something more sensible, like ask how many celebrities are there in our data of a given name using <b>value_counts()</b>.

In [49]:
name_count = celebrity_height_df["firstname"].value_counts()

name_count

firstname
Michael    84
John       76
James      64
David      59
Robert     50
           ..
Kareem      1
Wilt        1
Carel       1
Tiny        1
Montell     1
Name: count, Length: 2032, dtype: int64

Now, let's suppose that we want to do something more complicated.

Say that we want to compute the ratio of each celebrity's height to the average height of other celebrities with their same first name.

In [50]:
average_height = celebrity_height_df.groupby("firstname").mean(numeric_only = True)

celebrities_indexed_by_name = celebrity_height_df.set_index("firstname")

fraction_height_df = celebrities_indexed_by_name / average_height

fraction_height_df

,feet,ftin,fullname,gender,id,inches,inches_only,lastname,meters,midname
firstname,,,,,,,,,,
A,1.0,NaN,NaN,NaN,0.092384,0.222222,0.933333,NaN,0.933333,NaN
A,1.0,NaN,NaN,NaN,1.907616,1.777778,1.066667,NaN,1.066667,NaN
A. J.,1.0,NaN,NaN,NaN,0.845873,0.896552,0.988848,NaN,0.988848,NaN
A. J.,1.0,NaN,NaN,NaN,1.154127,1.103448,1.011152,NaN,1.011152,NaN
ANT,1.0,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,NaN
...,...,...,...,...,...,...,...,...,...,...
Zoe,1.0,NaN,NaN,NaN,1.172064,1.147541,1.013616,NaN,1.013616,NaN
Zoie,1.0,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,NaN
Zooey,1.0,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,NaN
Zsa,1.0,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,NaN
Zuleikha,1.0,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,NaN

---

In the above example, we divided all the values in "celebrities_indexed_by_name" with all the values in "average_height".

Whenever there was a numeric value, the result was straight forward. However, non-numeric values can't be divided and thus gave us "NaN" or "Not a Number".

Let's redo that, but instead of dividing all of the values, lets just divide the "inches_only" columns and create a new column with the ratio.

To accomplish this, we are first going to use <b>reindex()</b> to organize the DataFrame based on firstname and fullname.

---

In [51]:
df_indexed_by_firstname_and_fullname = celebrity_height_df.set_index(["firstname", "fullname"])
df_indexed_by_firstname_and_fullname

,,id,midname,lastname,ftin,feet,inches,meters,gender,inches_only
firstname,fullname,,,,,,,,,
Verne,Verne Troyer,1,NaN,Troyer,2ft 8in,2,8.00,0.81280,M,32.00
Herve,Herve Villechaize,8,NaN,Villechaize,3ft 10in,3,10.00,1.16840,M,46.00
David,David Rappaport,9,NaN,Rappaport,3ft 11in,3,11.00,1.19380,M,47.00
Tony,Tony Cox,2,NaN,Cox,3ft 6in,3,6.00,1.06680,M,42.00
Warwick,Warwick Davis,3,NaN,Davis,3ft 6in,3,6.00,1.06680,M,42.00
...,...,...,...,...,...,...,...,...,...,...
General,General Height,5499,NaN,Height,7ft 6.5in,7,6.50,2.29870,NaN,90.50
Matthew,Matthew McGrory,5498,NaN,McGrory,7ft 6in,7,6.00,2.28600,M,90.00
Sandy,Sandy Allen,5500,NaN,Allen,7ft 7.25in,7,7.25,2.31775,F,91.25
Sun,Sun Ming Ming,5501,Ming,Ming,7ft 8.75in,7,8.75,2.35585,NaN,92.75
Robert,Robert Wadlow,5502,NaN,Wadlow,8ft 11in,8,11.00,2.71780,M,107.00