<a href="https://colab.research.google.com/github/dr-bankert-augustana/PHYS_200/blob/main/Lessons/Module_1/PHYS_200_Lesson_1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a name="Notebook-Start"></a>

---

<font size = 7> <b> Lesson 1.4 (Pandas and DataFrames) </b> </font>

---

<font size = 5> <b> Notebook Index </b> </font>

1.  [Learning Outcomes](#Learning-Outcomes)

2.  [Introduction](#Introduction)

3.  [Numpy](#Numpy)

4.  [Scipy](#Scipy)

5.  [Matplotlib](#Matplotlib)

6.  [Seaborn](#Seaborn)

7.  [Appendix A: New Term Definitions](#Appendix-Definitions)
$
\newcommand{\lsum}{\displaystyle \sum\limits_{i=1}^{N}}
\newcommand{\parens}[1]{\left(#1\right)}
\newcommand{\dsfrac}[2]{\displaystyle\frac{#1}{#2}}
\newcommand{\dpfrac}[2]{\displaystyle\parens{\frac{#1}{#2}}}
\newcommand{\parderiv}[2]{\dsfrac{\partial #1}{\partial #2}}
\newcommand{\spc}{\hspace{0.1 pc}}
\newcommand{\ra}{\Rightarrow}
\newcommand{\of}[1]{{\scriptsize (#1)}}
\newcommand{\rule}{\Huge \hspace{-0.2 pc} \displaystyle\frac{\hspace{20 pc}}{\hspace{20 pc}}}
\newcommand{\mps}{\spc \frac{\textrm{m}}{\textrm{s}}}
\newcommand{\mpss}{\spc \frac{\textrm{m}}{\textrm{s}^2}}
$

<a name="Learning-Outcomes"></a>

---

<font size = 6> <b> 1. Learning Outcomes </b> </font>

---

By the end of this lesson, students will:

  * <b>Understand</b> what libraries are and why they are useful.

  * <b>Know</b> how to import and use popular scientific libraries: NumPy, SciPy, Matplotlib, and Seaborn.

  * <b>Use</b> NumPy for numerical operations.

  * <b>Use</b> SciPy for scientific computations.

  * <b>Generate</b> basic plots using Matplotlib and Seaborn.

[Return to Top](#Notebook-Start)

<a name="Introduction"></a>

---

<font size = 6> <b> 2. Introduction </b> </font>

---

<font size = 5> <b> 2.1 What is Pandas? </b> </font>

<p align="justify">
In computational physics (and any kind of scientific computing) managing, analyzing, and visualizing data efficiently is essential. The Pandas library in Python is a powerful and flexible tool designed specifically for data manipulation and analysis. At its core, Pandas introduces two primary data structures.
</p>

  * The <a href = #Definition-Series></b>Series</b></a> (a one-dimensional array)
  
  * The <a href = #Definition-Series></b>DataFrame</b></a> (a two-dimensional table similar to an Excel spreadsheet).
  
<br>

<p align="justify">
These new data structures allow us to label our data, perform complex operations with simple syntax, and handle missing values or mixed data types gracefully.
</p>

[Return to Top](#Notebook-Start)

<a name="Creating-DF"></a>

---

<font size = 6> <b> 3. Creating DataFrames </b> </font>

---

<font size=5><b>3.1 Creating DataFrames From Dictionaries</b></font>

<p align="justify">
One of the most straightforward ways to create a DataFrame in Pandas is by using a Python dictionary. In this approach, each key in the dictionary represents a column name, and the corresponding value is a list (or array) containing the data for that column. Pandas automatically aligns these values by row, as long as the lists are of equal length.
</p>

<br>

<p align="justify">
This method is especially useful when you already have structured data in Python (for example, experimental measurements or simulation results stored in variables) and you want to organize them into a tabular format for further analysis.
</p>

<br>

<b>Code Example:</b>

In the following code cell, we create a simple DataFrame from some synthetic experimental data.

In [2]:
# Import the Pandas Library:

import pandas as pd

# Create a dictionary of data:

data = {
    "Time (s)": [0, 1, 2, 3, 4],
    "Position (m)": [0, 2.5, 10, 22.5, 40],
    "Velocity (m/s)": [0, 5, 10, 15, 20]
}

# Convert the dictionary into a DataFrame:

df = pd.DataFrame(data)

# Display the DataFrame:

display(df)

   Time (s)  Position (m)  Velocity (m/s)
0         0           0.0               0
1         1           2.5               5
2         2          10.0              10
3         3          22.5              15
4         4          40.0              20

<b>Understanding the Output</b>

<p align="justify">
This printed table looks very similar to what you'd see in a spreadsheet like Excel or Google Sheets:
</p>

  * <b>Columns:</b> Each column corresponds to one of the keys from the dictionary. In this case, we have three columns: <code>Time (s)</code>, <code>Position (m)</code>, and <code>Velocity (m/s)</code>. These serve the same purpose as column headers in a spreadsheet, labeling the type of data in each column.

  * <b>Rows:</b> Each row contains a single set of related data points; one time value, one position, and one velocity. These rows represent observations or measurements taken at different points in time.

  * <b>Index column (on the far left):</b> By default, Pandas automatically adds an index column starting from 0. This index uniquely identifies each row, similar to row numbers in a spreadsheet. While it doesn't carry physical meaning in this example, it becomes very useful when accessing or referencing specific rows programmatically.

<br>

<p align="justify">
So, in essence, the Pandas DataFrame behaves much like a digital spreadsheet, but with the added power of Python. As we see in this lesson, you can apply mathematical operations, filter rows, compute statistics, and generate plots all from this structured format, making it a key tool in your computational physics toolkit.
</p>

<center>$\rule$</center>
<font size=5><b>3.2 Creating a DataFrame from a CSV File</b></font>

<p align="justify">
In real-world physics work, it's common to store data in external files; especially CSV (Comma-Separated Values) files. These are simple text files where each line represents a row of data, and values are separated by commas. Think of it as a stripped-down spreadsheet that can be easily shared and read by many programs. In fact, you can export a spreadsheet from any common program (such as Excel, Google Sheets, etc) as a CSV file.
</p>

<br>

<p align="justify">
Pandas makes it incredibly easy to read data from a CSV file and convert it into a DataFrame using the <code>read_csv()</code> function.
</p>

<br>

<b>Code Example:</b>

In the following code cell, we read in the data from a CSV file into a Pandas DataFrame.

In [5]:
# Set the location of the CSV file (can be local or a website):

url = "https://raw.githubusercontent.com/dr-bankert-augustana/PHYS_200/refs/heads/main/Data/Module_1/celebrity-heights.csv"

# Turn the CSV data into a Pandas DataFrame:

celebrity_height_df = pd.read_csv(url)

# Display the DataFrame:

display(celebrity_height_df)

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.00,0.81280,M
1,8,Herve,NaN,Villechaize,Herve Villechaize,3ft 10in,3,10.00,1.16840,M
2,9,David,NaN,Rappaport,David Rappaport,3ft 11in,3,11.00,1.19380,M
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.00,1.06680,M
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.00,1.06680,M
...,...,...,...,...,...,...,...,...,...,...
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M

[Return to Top](#Notebook-Start)

<a name="Explore-DF"></a>

---

<font size = 6> <b> 4. Exploring a DataFrame </b> </font>

---

<font size=5><b>4.1 Methods for Exploring the DataFrame</b></font>

<p align="justify">
Once you've loaded data into a Pandas DataFrame (whether from a dictionary, CSV file, or another source) it's important to understand what's in it and whether it looks right before jumping into analysis. Pandas provides several built-in methods to help us quickly explore the dataset.
</p>

<center>$\rule$</center>
<font size=5><b>4.2 <code>info()</code>: Structure and Metadata</b></font>

This method gives you a concise summary of the DataFrame’s structure, including:

  * The number of rows and columns

  * Column names and data types (int64, float64, object, etc.)

  * Number of non-null (i.e. non-missing) values in each column

  * Memory usage

<br>

<p align="justify">
<b>Why it's useful:</b> Helps you quickly check for missing data and see if the data types are appropriate (e.g. no text where numbers should be).
</p>

<br>

<b>Code Example:</b>

In the following code cell, we use <code>info()</code> to look at our celebrity heights DataFrame.

In [7]:
# Display the Output of info():

display(celebrity_height_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5502 entries, 0 to 5501
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         5502 non-null   int64
 1   firstname  5502 non-null   object
 2   midname    340 non-null    object
 3   lastname   5416 non-null   object
 4   fullname   5502 non-null   object
 5   ftin       5502 non-null   object
 6   feet       5502 non-null   int64
 7   inches     5502 non-null   float64
 8   meters     5502 non-null   float64
 9   gender     4988 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 430.0+ KB

None

<center>$\rule$</center>
<font size=5><b>4.3 <code>df.describe()</code>: Summary Statistics</b></font>

This method computes common statistical summaries for each numeric column, such as:

* Count

* Mean

* Standard deviation

* Min and max

* 25th, 50th (median), and 75th percentiles

<br>

<b>Why it's useful</b>: Provides a quick overview of the data's distribution and helps spot unusual values (e.g., extreme outliers or zero variance).

<br>

<b>Code Example:</b>

In the following code cell, we use <code>describe()</code> to look at our celebrity heights DataFrame.

<center>$\rule$</center>
<font size=5><b>4.4 <code>head(n)</code>: Display First n Rows (Default: 5)</b></font>

Displays the first few rows of the DataFrame. This is often your first stop after loading data to verify that everything looks as expected (column names, data format, etc.).

<br>

<b>Code Example:</b>

In the following code cell, we use <code>head(n)</code> to look at our celebrity heights DataFrame.

In [10]:
# Display the first 5 rows of the celebrity heights DataFrame:

print("First 5 rows:")

display(celebrity_height_df.head())

print()

# Display the first 10 rows of the celebrity heights DataFrame:

print("First 10 rows:")

display(celebrity_height_df.head(10))

First 5 rows:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.0,0.8128,M
1,8,Herve,NaN,Villechaize,Herve Villechaize,3ft 10in,3,10.0,1.1684,M
2,9,David,NaN,Rappaport,David Rappaport,3ft 11in,3,11.0,1.1938,M
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.0,1.0668,M
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.0,1.0668,M

First 10 rows:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.0,0.81280,M
1,8,Herve,NaN,Villechaize,Herve Villechaize,3ft 10in,3,10.0,1.16840,M
2,9,David,NaN,Rappaport,David Rappaport,3ft 11in,3,11.0,1.19380,M
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.0,1.06680,M
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.0,1.06680,M
5,4,Phil,NaN,Fondacaro,Phil Fondacaro,3ft 6in,3,6.0,1.06680,M
6,5,Michael,J,Anderson,Michael J Anderson,3ft 7in,3,7.0,1.09220,M
7,6,Kenny,NaN,Baker,Kenny Baker,3ft 8in,3,8.0,1.11760,M
8,7,Billy,NaN,Barty,Billy Barty,3ft 9in,3,9.0,1.14300,M
9,10,Kiran,NaN,Shah,Kiran Shah,4ft 1.7in,4,1.7,1.26238,F

<center>$\rule$</center>
<font size=5><b>4.5 <code>tail(n)</code>: Display Last n Rows (Default: 5)</b></font>

Displays the last few rows of the DataFrame. This is useful to:

  * See the end of a time series

  * Verify that data loaded completely

  * Check for anomalies or formatting issues at the bottom of the file

<br>

<b>Code Example:</b>

In the following code cell, we use <code>tail(n)</code> to look at our celebrity heights DataFrame.

In [11]:
# Display the last 5 rows of the celebrity heights DataFrame:

print("Last 5 rows:")

display(celebrity_height_df.tail())

print()

# Display the last 10 rows of the celebrity heights DataFrame:

print("Last 10 rows:")

display(celebrity_height_df.tail(10))

Last 5 rows:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M

Last 10 rows:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
5492,5490,Dalip,NaN,Singh,Dalip Singh,7ft 1in,7,1.00,2.15900,NaN
5493,5491,Football,NaN,Soccer,Football Soccer,7ft 1in,7,1.00,2.15900,NaN
5494,5492,Ian,NaN,Whyte,Ian Whyte,7ft 1in,7,1.00,2.15900,M
5495,5496,Kevin,Peter,Hall,Kevin Peter Hall,7ft 2in,7,2.00,2.18440,M
5496,5497,Ming,NaN,Yao,Ming Yao,7ft 5in,7,5.00,2.26060,F
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M

<center>$\rule$</center>
<font size=5><b>4.6 Other Useful Commands For Investigating DataFrames</b></font>

  * <b>df.columns</b>:
  
    * Returns a list-like object containing the column labels.

    * Useful for checking column names or looping through columns.

  * <b>df.index</b>:

    * Returns the row index of the DataFrame (default is a RangeIndex).

    * Important if you're dealing with custom indices like timestamps or labels.

  * <b>df.shape</b>:

    * Returns a tuple representing the dimensions of the DataFrame: (rows, columns).

  * <b>df.dtypes</b>:

    * Shows the data type of each column (e.g., float64, int64, object).

    * Helpful when debugging unexpected behavior in calculations.

  * <b>df.nunique()</b>:

    * Returns the number of unique values in each column.

    * Good for identifying categorical vs. continuous data, or detecting duplicates.

  * <b>df.isnull().sum()</b>:

    * Identifies missing values by column.

    * Essential for cleaning data before analysis or plotting.

  * <b>df.sample(n)</b>:

    * Returns a random sample of n rows from the DataFrame.

    * Great for large datasets when you just want to inspect a few random entries.

  * <b>df["column_name"].value_counts()</b>:

    * For a single column, shows how often each unique value appears (useful for categorical or discrete data).

[Return to Top](#Notebook-Start)

<a name="Select-DF"></a>

---

<font size = 6> <b> 5. Selecting Data in a DataFrame </b> </font>

---

<font size=5><b>5.1 Bracket Notation []</b></font>

<p align="justify">
Once we have loaded and explored our DataFrame, the next step is accessing specific columns or subsets of data. One of the most common and flexible ways to do this is using bracket selection, which looks like: <code>DataFrame[selector]</code>
</p>

<br>

<p align="justify">
Depending on what we put inside the brackets, we can select a column, multiple columns, or filter rows using logical conditions.
</p>

<center>$\rule$</center>
<font size=5><b>5.2 Selecting a Single Column</b></font>

<p align="justify">
If we pass a string (column name) inside the brackets, Pandas returns a Series (a one-dimensional view of that column). This works like selecting a column in a spreadsheet by its header. The result behaves like a list but with labels (index) attached.
</p>

<br>

><b>Note:</b><p align="justify">
We can also call up a column by using: <code>DF_Name.Column_Name</code>
</p>

<br>

<b>Code Example:</b>

In [14]:
# Select the 'firstname' column of the celebrity heights data:

first_names = celebrity_height_df['firstname']

# Display the firstnames data:

display(first_names)

# Select the 'lastname' column of the celebrity heights data:

last_names = celebrity_height_df.lastname

# Display the lastnames data:

display(last_names)

0         Verne
1         Herve
2         David
3          Tony
4       Warwick
         ...
5497    General
5498    Matthew
5499      Sandy
5500        Sun
5501     Robert
Name: firstname, Length: 5502, dtype: object

0            Troyer
1       Villechaize
2         Rappaport
3               Cox
4             Davis
           ...
5497         Height
5498        McGrory
5499          Allen
5500           Ming
5501         Wadlow
Name: lastname, Length: 5502, dtype: object

<center>$\rule$</center>
<font size=5><b>5.3 Selecting a Multiple Columns</b></font>

<p align="justify">
To select more than one column, pass in a list of column names inside the brackets: <code>subset_df = df[[column_1, column_2]]</code>. Now you get a new DataFrame with just those columns. Similar to hiding other columns in a spreadsheet.
</p>

<br>

<b>Code Example:</b>

In [15]:
# Select the 'firstname' and 'lastname' columns of the celebrity heights data:

names = celebrity_height_df[['firstname', 'lastname']]

# Display the subset data:

display(names)

     firstname     lastname
0        Verne       Troyer
1        Herve  Villechaize
2        David    Rappaport
3         Tony          Cox
4      Warwick        Davis
...        ...          ...
5497   General       Height
5498   Matthew      McGrory
5499     Sandy        Allen
5500       Sun         Ming
5501    Robert       Wadlow

[5502 rows x 2 columns]

<center>$\rule$</center>
<font size=5><b>5.4 Selecting Rows with Logical Conditions</b></font>

<p align="justify">
You can also use bracket selection with boolean expressions to filter rows. This is incredibly powerful for working with physical measurements or simulation outputs. This is called using a <b>Boolean Mask</b>. Example: <code>subset = df[boolean_mask]</code>. This filters the DataFrame and only returns rows that meet the condition, just like using filters in Excel or Google Sheets.
</p>

><b>Note:</b><p align="justify">
You can build more complex filters by combining multiple conditions.
</p>

<br>

<b>Code Example:</b>

In [20]:
# Create a subset of people who are over 2.2 meters tall:

tall_people = celebrity_height_df[celebrity_height_df['meters'] > 2.2]

# Display the subset data:

print("Tall People:")
display(tall_people)
print()

# Create a subset of people who are between 1.6 and 1.7 meters tall:

medium_tall_people = celebrity_height_df[(celebrity_height_df['meters'] > 1.6) & (celebrity_height_df['meters'] < 1.7)]

# Display the subset data:

print("Medium Tall People:")
display(medium_tall_people)

Tall People:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
5496,5497,Ming,NaN,Yao,Ming Yao,7ft 5in,7,5.00,2.26060,F
5497,5499,General,NaN,Height,General Height,7ft 6.5in,7,6.50,2.29870,NaN
5498,5498,Matthew,NaN,McGrory,Matthew McGrory,7ft 6in,7,6.00,2.28600,M
5499,5500,Sandy,NaN,Allen,Sandy Allen,7ft 7.25in,7,7.25,2.31775,F
5500,5501,Sun,Ming,Ming,Sun Ming Ming,7ft 8.75in,7,8.75,2.35585,NaN
5501,5502,Robert,NaN,Wadlow,Robert Wadlow,8ft 11in,8,11.00,2.71780,M

Medium Tall People:

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
1252,591,Jillian,NaN,Barberie,Jillian Barberie,5ft 3.25in,5,3.25,1.60655,F
1253,592,Vanessa,NaN,Paradis,Vanessa Paradis,5ft 3.25in,5,3.25,1.60655,F
1254,593,Annabella,NaN,Sciorra,Annabella Sciorra,5ft 3.25in,5,3.25,1.60655,F
1255,594,Amy,NaN,Adams,Amy Adams,5ft 3.5in,5,3.50,1.61290,F
1256,595,Samaire,NaN,Armstrong,Samaire Armstrong,5ft 3.5in,5,3.50,1.61290,NaN
...,...,...,...,...,...,...,...,...,...,...
2672,1694,Henry,NaN,Winkler,Henry Winkler,5ft 6in,5,6.00,1.67640,M
2673,1695,Kate,NaN,Winslet,Kate Winslet,5ft 6in,5,6.00,1.67640,F
2674,1696,Evan,Rachel,Wood,Evan Rachel Wood,5ft 6in,5,6.00,1.67640,M
2675,1697,Bill,NaN,Wyman,Bill Wyman,5ft 6in,5,6.00,1.67640,M
2676,1698,Loretta,NaN,Young,Loretta Young,5ft 6in,5,6.00,1.67640,F